#!/usr/bin/env python3
"""Rank source-only Story recovery gaps without inventing scene order.

The queue reuses the strict partial-order builder, then measures where original
game data could still improve coverage: isolated/weak scenes, source cycles,
untyped multi-scene LevelScript contexts, quests without strict Story
attachment, unresolved source nodes, and unverified option groups.  Main-story
(``e``) missions sort before the other established priority buckets.
"""
from __future__ import annotations

import base64
import binascii
import hashlib
import json
import re
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path
from typing import Any, Iterator


ROOT = Path(__file__).resolve().parents[3]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

from common import (  # noqa: E402
    combined_non_mission_content_keys,
    md_escape,
    non_mission_content_keys,
    read_json,
    resolve_installed_native_inputs,
    safe_key,
    sha256_file,
    write_report_json,
    write_text_if_changed,
)
from story_builder.source_story_partial_order import (  # noqa: E402
    build_report as build_partial_order_report,
    load_mission_payload_with_variants,
)
from .contracts import (  # noqa: E402
    BUCKET_ORDER,
    FRONTIER_ORDER,
    LEVELDATA_INTERACTIVE_HORN_MAPPING_ID,
    LEVELDATA_INTERACTIVE_HORN_NATIVE_MAPPING_ID,
    LEVELDATA_INTERACTIVE_HORN_TEMPLATE_SHA256,
    LEVELDATA_INTERACTIVE_NARRATIVE_MAPPING_ID,
    LEVELSCRIPT_INTERACTIVE_NARRATIVE_MAPPING_ID,
    SCHEMA,
    SCORE_WEIGHTS,
    STORY_BINDING_COVERAGE_SCHEMA_VERSION,
    priority_bucket,
    target_set_sha256,
)
from story_builder.animestudio_story_objects import (
    CARRIER_REPORT_PATH,
    HIERARCHY_REPORT_PATH,
    REVERSE_REPORT_PATH,
)
from story_builder.level_bindings import (  # noqa: E402
    LEVELSCRIPT_NATIVE_ACTION_MAPPING_ID,
    LEVELSCRIPT_NATIVE_EXACT_CONTROL_PATH_STATUSES,
    _load_levelscript_binding_data,
    _levelscript_native_control_paths_to_record,
    build_levelscript_unhosted_reading_popup_receiver_index,
    decode_levelscript_native_action_topology,
    parse_leveldata_levelscript_brief_dictionary,
)
from story_builder.levelscript_binary import (  # noqa: E402
    decode_levelscript_binary_summary,
    decode_levelscript_record_payload,
    decode_levelscript_task_conditions,
    extract_levelscript_uid_records,
    levelscript_action_map_membership,
    levelscript_record_semantic_key,
)
from story_builder.anime_assets import (  # noqa: E402
    recover_dialog_tree_definition_evidence,
    recover_dialog_tree_prime_reachable_carriers_for_parent,
)
from story_builder.mission_recovery import natural_key  # noqa: E402
from story_builder.mission_assets import (  # noqa: E402
    mission_runtime_source_summary,
    select_complete_mission_runtime_root,
)


from .data import (
    CORE_STORY_NODE_KINDS,
    KNOWN_NON_PLAYBACK_ACTIONS,
    KNOWN_NON_PLAYBACK_MAPPING_ID,
    NPC_PROXY_DIALOG_SELECTION_MAPPING_ID,
    NON_OWNING_DIAGNOSTIC_QUEST_ATTACH_SOURCES,
    NPC_PROXY_DIALOG_SELECTION_GAMEASSEMBLY_SHA256,
    NPC_PROXY_TRACKING_INFO_TYPE,
    NPC_PROXY_TRACKING_INFO_FIELDS,
    DIALOG_TREE_NARRATIVE_CONNECTION_MAPPING_ID,
    DIALOG_TREE_TRUNK_GROUP_MAPPING_ID,
    DIALOG_TREE_TRUNK_NATIVE_CONSUMERS,
    OFFLINE_EXHAUSTION_MAPPING_ID,
    OFFLINE_EXHAUSTION_GAMEASSEMBLY_SHA256,
    OFFLINE_EXHAUSTION_ABSENT_BINARY_TOKENS,
    OFFLINE_EXHAUSTION_MISSION_BRANCH_CONTEXTS,
    OFFLINE_EXHAUSTION_MISSION_RELATED_ORIGINAL_DATA,
    OFFLINE_EXHAUSTION_MISSION_LINEAR_CONTEXTS,
    OFFLINE_EXHAUSTION_MISSION_TOPOLOGY_CONTEXTS,
    OFFLINE_EXHAUSTION_LEVELDATA_DIALOG_BRANCH_CONTEXTS,
    OFFLINE_EXHAUSTION_EMPTY_LEVELSCRIPT_CONTEXTS,
    OFFLINE_EXHAUSTION_LEVELSCRIPT_TASK_CONSUMERS,
    OFFLINE_EXHAUSTION_REVERSE_PPTR_MAPPING_ID,
    OFFLINE_EXHAUSTION_METADATA_SHA256,
    OFFLINE_EXHAUSTION_RADIO_TABLE_SHA256,
    OFFLINE_EXHAUSTION_AUDIO_DIALOG_SHA256,
    OFFLINE_EXHAUSTION_NUM_ID_STR_TABLE_SHA256,
    OFFLINE_EXHAUSTION_STR_ID_NUM_TABLE_SHA256,
    OFFLINE_EXHAUSTION_TEXT_TABLE_SHA256,
    OFFLINE_EXHAUSTION_DIALOG_TEXT_TABLE_SHA256,
    OFFLINE_EXHAUSTION_DIALOG_OPTION_TABLE_SHA256,
    OFFLINE_EXHAUSTION_DIALOG_SUMMARY_MAP_TABLE_SHA256,
    OFFLINE_EXHAUSTION_DIALOG_SUMMARY_TABLE_SHA256,
    OFFLINE_EXHAUSTION_READING_POPUP_TABLE_SHA256,
    OFFLINE_EXHAUSTION_RICH_CONTENT_TABLE_SHA256,
    OFFLINE_EXHAUSTION_PRTS_ALL_ITEM_TABLE_SHA256,
    OFFLINE_EXHAUSTION_PRTS_RECORD_TABLE_SHA256,
    OFFLINE_EXHAUSTION_PRTS_READING_TABLE_SHA256,
    OFFLINE_EXHAUSTION_SNS_DIALOG_TABLE_SHA256,
    OFFLINE_EXHAUSTION_SNS_OPTION_TABLE_SHA256,
    OFFLINE_EXHAUSTION_NPC_PROXY_EX_TABLE_SHA256,
    OFFLINE_EXHAUSTION_NPC_PROXY_TABLE_SHA256,
    OFFLINE_EXHAUSTION_SNS_CHAT_TABLE_SHA256,
    OFFLINE_EXHAUSTION_DIALOG_ID_SOURCE_SHA256,
    OFFLINE_EXHAUSTION_DIALOG_ID_INDEX_SHA256,
    OFFLINE_EXHAUSTION_TIMELINE_LINE_ORDERS_SHA256,
    QUEST_ATTACHMENT_DIAGNOSTIC_MAPPING_ID,
    QUEST_ATTACHMENT_DIAGNOSTIC_SOURCE_PATHS,
    QUEST_ATTACHMENT_DIAGNOSTIC_SOURCE_HASHES,
    QUEST_ATTACHMENT_DIAGNOSTIC_DECLARATIONS,
    OFFLINE_EXHAUSTION_E11M4_CUTSCENE,
    OFFLINE_EXHAUSTION_E11M1_TEXT_ONLY_CUTSCENE,
    OFFLINE_EXHAUSTION_TEXT_ONLY_CUTSCENES,
    OFFLINE_EXHAUSTION_SNS_DEFINITIONS,
    OFFLINE_EXHAUSTION_E11M1_PRESENTATION_CUTSCENES,
    OFFLINE_EXHAUSTION_CUTSCENES_BY_MISSION,
    OFFLINE_EXHAUSTION_REVERSE_HOST_COUNTS,
    OFFLINE_EXHAUSTION_CUTSCENE_DEFINITIONS,
    OFFLINE_EXHAUSTION_GAMEOBJECT_ROW_COUNTS,
    OFFLINE_EXHAUSTION_ROOT_PLAYBACK_ALIASES,
    OFFLINE_EXHAUSTION_DIALOG_DEFINITIONS,
    OFFLINE_EXHAUSTION_POSITIVE_DIALOG_KEYS,
    OFFLINE_EXHAUSTION_TEXT_ONLY_DIALOGS,
    OFFLINE_EXHAUSTION_DIALOG_ROW_FIELDS,
    OFFLINE_EXHAUSTION_E11M4_RADIOS,
    OFFLINE_EXHAUSTION_E10M4_RADIOS,
    OFFLINE_EXHAUSTION_E11M1_RADIOS,
    OFFLINE_EXHAUSTION_E11M6_RADIOS,
    OFFLINE_EXHAUSTION_E11M2_RADIOS,
    OFFLINE_EXHAUSTION_E11M5_RADIOS,
    OFFLINE_EXHAUSTION_E9M2_RADIOS,
    OFFLINE_EXHAUSTION_E9M3_RADIOS,
    OFFLINE_EXHAUSTION_E9M4_RADIOS,
    OFFLINE_EXHAUSTION_E6M3_RADIOS,
    OFFLINE_EXHAUSTION_E1M2_RADIOS,
    OFFLINE_EXHAUSTION_E1M3_RADIOS,
    OFFLINE_EXHAUSTION_E1M4_RADIOS,
    OFFLINE_EXHAUSTION_E1M5_RADIOS,
    OFFLINE_EXHAUSTION_E1M6_RADIOS,
    OFFLINE_EXHAUSTION_E1M10_RADIOS,
    OFFLINE_EXHAUSTION_E7M2_RADIOS,
    OFFLINE_EXHAUSTION_E6M4_RADIOS,
    OFFLINE_EXHAUSTION_E6M5_RADIOS,
    OFFLINE_EXHAUSTION_E7M3_RADIOS,
    OFFLINE_EXHAUSTION_E11M3_RADIOS,
    OFFLINE_EXHAUSTION_E11M8_RADIOS,
    OFFLINE_EXHAUSTION_E3M2_RADIOS,
    OFFLINE_EXHAUSTION_E3M1_RADIOS,
    OFFLINE_EXHAUSTION_E3M3_RADIOS,
    OFFLINE_EXHAUSTION_E0M0_RADIOS,
    OFFLINE_EXHAUSTION_E2M4_RADIOS,
    OFFLINE_EXHAUSTION_E2M5_RADIOS,
    OFFLINE_EXHAUSTION_E2M6_RADIOS,
    OFFLINE_EXHAUSTION_E2M7_RADIOS,
    OFFLINE_EXHAUSTION_E2M2_RADIOS,
    OFFLINE_EXHAUSTION_E2M3_RADIOS,
    OFFLINE_EXHAUSTION_E5M2_RADIOS,
    OFFLINE_EXHAUSTION_E5M3_RADIOS,
    OFFLINE_EXHAUSTION_E5M4_RADIOS,
    OFFLINE_EXHAUSTION_E5M1_RADIOS,
    OFFLINE_EXHAUSTION_E5M5_RADIOS,
    OFFLINE_EXHAUSTION_E6M1_RADIOS,
    OFFLINE_EXHAUSTION_E6M2_RADIOS,
    OFFLINE_EXHAUSTION_E3M4_RADIOS,
    OFFLINE_EXHAUSTION_E4M1_RADIOS,
    OFFLINE_EXHAUSTION_E4M1D5_RADIOS,
    OFFLINE_EXHAUSTION_E7M4_RADIOS,
    OFFLINE_EXHAUSTION_E8M2_RADIOS,
    OFFLINE_EXHAUSTION_E8M1_RADIOS,
    OFFLINE_EXHAUSTION_E8M3_RADIOS,
    OFFLINE_EXHAUSTION_E8M5_RADIOS,
    OFFLINE_EXHAUSTION_E10M1_RADIOS,
    OFFLINE_EXHAUSTION_E10M2_RADIOS,
    OFFLINE_EXHAUSTION_A1M6D1_RADIOS,
    OFFLINE_EXHAUSTION_A1M6D2_RADIOS,
    OFFLINE_EXHAUSTION_A1M6D3_RADIOS,
    OFFLINE_EXHAUSTION_A1M8D3_RADIOS,
    OFFLINE_EXHAUSTION_GM02M2_RADIOS,
    OFFLINE_EXHAUSTION_GM02M3_RADIOS,
    OFFLINE_EXHAUSTION_GM02M14_RADIOS,
    OFFLINE_EXHAUSTION_GM02M15_RADIOS,
    OFFLINE_EXHAUSTION_GM02M21_RADIOS,
    OFFLINE_EXHAUSTION_GM02M13_RADIOS,
    OFFLINE_EXHAUSTION_GM02M17_RADIOS,
    OFFLINE_EXHAUSTION_GM01M4_RADIOS,
    OFFLINE_EXHAUSTION_GM01M6_RADIOS,
    OFFLINE_EXHAUSTION_GM01M7_RADIOS,
    OFFLINE_EXHAUSTION_GM01M16_RADIOS,
    OFFLINE_EXHAUSTION_GM01M20_RADIOS,
    OFFLINE_EXHAUSTION_GM01M22_RADIOS,
    OFFLINE_EXHAUSTION_GM01M24_RADIOS,
    OFFLINE_EXHAUSTION_GM01M25_RADIOS,
    OFFLINE_EXHAUSTION_GM01M26_RADIOS,
    OFFLINE_EXHAUSTION_GM01M27_RADIOS,
    OFFLINE_EXHAUSTION_GM01M17_RADIOS,
    OFFLINE_EXHAUSTION_GM01M3_RADIOS,
    OFFLINE_EXHAUSTION_GM01M5_RADIOS,
    OFFLINE_EXHAUSTION_GM02M1_RADIOS,
    OFFLINE_EXHAUSTION_GM02M20_RADIOS,
    OFFLINE_EXHAUSTION_GM02M23_RADIOS,
    OFFLINE_EXHAUSTION_RADIOS_BY_MISSION,
    OFFLINE_EXHAUSTION_RADIO_CONTEXTS,
    OFFLINE_EXHAUSTION_RADIO_AUDIO_VARIANTS,
    OFFLINE_EXHAUSTION_RADIO_MISSING_AUDIO_IDS,
    OFFLINE_EXHAUSTION_RADIO_ROW_FIELDS,
    OFFLINE_EXHAUSTION_RADIO_LINE_FIELDS,
    READING_POPUP_ROW_FIELDS,
    RICH_CONTENT_ROW_FIELDS,
    RICH_CONTENT_ITEM_FIELDS,
    LOCALIZED_TEXT_FIELDS,
    DIALOG_OPTION_ROW_FIELDS,
)
from .providers import (
    DIRECT_OBJECTIVE_STORY_CONDITION_FIELDS,
    _build_mission_npc_proxy_tracking_index,
    _configured_game_assembly_path,
    _diagnostic_quest_attachments,
    _exact_levelscript_property_story_consumer,
    _flow,
    _flow_story_connections,
    _generic_mission_npc_proxy_tracking_contexts,
    _generic_registered_dialog_tree_definition_facts,
    _merge_exact_interaction_trigger_with_native_playback,
    _repo_source_path,
    _sha256_file,
    _strict_quest_attachments,
    _string_list,
    _timeline,
)
from .evidence import (
    NPC_PROXY_EX_LEGACY_ROW_FIELDS,
    NPC_PROXY_EX_ROW_FIELDS,
    NPC_PROXY_INFO_FIELDS,
    OFFLINE_EXHAUSTION_TEXT_DEFINITIONS,
    SERVER_PLACEHOLDER_CONTEXT_RELATIONS,
    SNS_CHAT_ROW_FIELDS,
    SNS_CONTENT_ROW_FIELDS,
    SNS_DIALOG_ROW_FIELDS,
    SNS_OPTION_ROW_FIELDS,
    _audit_source_index_diagnostics,
    _audit_sources_match_current_indexes,
    _blackbox_subgame_action_topology,
    _blackbox_subgame_task_topology,
    _classify_levelscript_condition_story_boundary,
    _classify_server_placeholder_story_boundary,
    _compose_registered_dialog_tree_npc_proxy_evidence,
    _configured_global_metadata_path,
    _core_isolated_target_missions,
    _declared_dialog_context_definitions,
    _dialog_parent_level_candidate,
    _dialog_text_partition_fragment_facts,
    _dialog_tree_branch_groups,
    _dialog_tree_terminal_option_routes,
    _generic_dialog_timeline_definition_facts,
    _generic_missionless_native_playback_facts,
    _generic_missionless_npc_proxy_dialog_facts,
    _generic_parent_dialog_level_context_facts,
    _generic_partial_dialog_row_consumer_exhaustion_facts,
    _generic_radio_definition_facts,
    _generic_reading_popup_definition_facts,
    _generic_registered_dialog_tree_trunk_group_facts,
    _generic_registered_table_dialog_definition_facts,
    _generic_text_table_only_cutscene_definition_facts,
    _generic_unlinked_sns_definition_facts,
    _generic_unregistered_dialog_definition_facts,
    _is_authored_sns_definition_candidate,
    _literal_absence_census,
    _localized_text_id,
    _memorypack_contains_exact_string,
    _mission_related_original_data_validation,
    _offline_radio_definition_validation_failure,
    _offline_text_definition_validation_failure,
    _present_literal_keys,
    build_general_quest_attachment_boundary_index,
    build_offline_exhaustion_index,
    build_quest_attachment_diagnostic_index,
    load_story_trigger_manifest_evidence,
    project_authored_story_content_keys,
)
from .model import (
    _bucket,
    _classify_levelscript_context_gaps,
    _closed_definition_only_isolated_scenes,
    _closed_exact_black_carrier_context_isolated_scenes,
    _closed_exact_composed_root_playback_isolated_scenes,
    _closed_exact_connected_context_isolated_scenes,
    _closed_exact_dialog_tree_embedded_context_isolated_scenes,
    _closed_exact_dialog_tree_embedded_isolated_scenes,
    _closed_exact_disconnected_dialog_tree_context_isolated_scenes,
    _closed_exact_lua_controller_playback_isolated_scenes,
    _closed_exact_native_context_isolated_scenes,
    _closed_exact_native_unordered_scenes,
    _closed_exact_runtime_config_isolated_scenes,
    _closed_exact_system_selector_isolated_scenes,
    _closed_exact_timeline_dialog_embedded_isolated_scenes,
    _closed_exact_timeline_foreign_dialog_isolated_scenes,
    _closed_non_mission_content_isolated_scenes,
    _connection_native_occurrences,
    _current_dialog_id_index_for_validation,
    _current_game_assembly_sha256_for_validation,
    _current_tracked_proxy_dialog_sources,
    _deferred_offline_exhausted_isolated_scenes,
    _exact_cross_owner_dialog_tree_narrative_context,
    _exact_cross_owner_levelscript_quest_playback,
    _exact_cross_owner_mission_condition_story_context,
    _exact_cross_owner_npc_proxy_segment_story_context,
    _exact_leveldata_story_context,
    _exact_typed_mission_state_transition_checks,
    _frontier_contributions,
    _generic_prime_reachable_dialog_dependency_facts,
    _generic_registered_dialog_non_owning_context_facts,
    _levelscript_context_gaps,
    _registered_parent_playback_routes_match,
    _validate_general_tracked_proxy_flow_context,
    build_gap_report,
    build_gap_row,
)
