#pragma kernel Readback

cbuffer _LightBinningConstants
{
    int _PunctualLightCount;
    int _NumTiles;
    int _ActualWidth;
    int _ActualHeight;
    float _TileSize;
    float _NumTilesX;
    float _NumTilesY;
    float _NumSliceZ;
    float _NearClipPlane;
    float _FarClipPlane;
    float _ZBinSlice;
    float _InvZBinSlice;
};

RWStructuredBuffer<uint> _EndfieldRecoveredLightBinningConstantsReadback;

[numthreads(1, 1, 1)]
void Readback(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    _EndfieldRecoveredLightBinningConstantsReadback[0] = asuint(_PunctualLightCount);
    _EndfieldRecoveredLightBinningConstantsReadback[1] = asuint(_NumTiles);
    _EndfieldRecoveredLightBinningConstantsReadback[2] = asuint(_ActualWidth);
    _EndfieldRecoveredLightBinningConstantsReadback[3] = asuint(_ActualHeight);
    _EndfieldRecoveredLightBinningConstantsReadback[4] = asuint(_TileSize);
    _EndfieldRecoveredLightBinningConstantsReadback[5] = asuint(_NumTilesX);
    _EndfieldRecoveredLightBinningConstantsReadback[6] = asuint(_NumTilesY);
    _EndfieldRecoveredLightBinningConstantsReadback[7] = asuint(_NumSliceZ);
    _EndfieldRecoveredLightBinningConstantsReadback[8] = asuint(_NearClipPlane);
    _EndfieldRecoveredLightBinningConstantsReadback[9] = asuint(_FarClipPlane);
    _EndfieldRecoveredLightBinningConstantsReadback[10] = asuint(_ZBinSlice);
    _EndfieldRecoveredLightBinningConstantsReadback[11] = asuint(_InvZBinSlice);
}
