"""Field order for the MemoryPack schemas used by maintained workflows."""

BUFF_MEMBER_COUNT = 30
# Current selected Endfield build serializes SkillData with 48 members.
# ``canCastInWater`` was added between ``canCastInAir`` and
# ``rootMotionCliffCheck``; the old 47-member table silently omitted it.
SKILL_MEMBER_COUNT = 48

MEMORYPACK_FIELD_SCHEMAS = {'BuffData': ['abilityEventAction',
              'addingCooldown',
              'applyTags',
              'attributeModifier',
              'blackboard',
              'buffEventAction',
              'damageModifier',
              'dispelConfig',
              'duration',
              'finishOnRepatriate',
              'globalModifier',
              'hasAddingCooldown',
              'hasIcon',
              'healModifier',
              'iconConfig',
              'id',
              'igniteEventAction',
              'ignoreCooldownWhenAdding',
              'ignoreTagImmune',
              'lifeType',
              'maxTriggerCnt',
              'onlyUseSelfTimeDilation',
              'poiseModifier',
              'shieldConfigs',
              'stackingSettings',
              'tagsAfterTriggerExtendBuffAction',
              'timelineActions',
              'triggerInterval',
              'useTimeDilationDt',
              'waitFirstTriggerInterval'],
 'InteractiveTemplateData': ['name',
                             'factionIndex',
                             'objectType',
                             'bornTag',
                             'componentList',
                             'delayRecyclePerformTime',
                             'delayToRecycleTime',
                             'enableBornFadeIn',
                             'fadeInTime',
                             'sendDieEvent',
                             'allGlobalSaveProperties',
                             'allMapSaveProperties',
                             'aoiRadiusType',
                             'configProperties',
                             'dataMap',
                             'facOccDis',
                             'hideInDialog',
                             'mountPoints',
                             'propertyIdToKeyMap',
                             'propertyKeyToIdMap',
                             'saveProperties',
                             'templateVariant',
                             'tempProperties',
                             'useGlobalVar',
                             'useMapVar'],
 'ModelViewStateControllerData': ['cameraSignalSourceAssetHashes',
                                  'clipAssetInfos',
                                  'effectIds',
                                  'emissiveConfigHashes',
                                  'modelAnimatorDatas',
                                  'modelId',
                                  'preTickAnimator'],
 'SkillData': ['actionGroupData',
               'aiExclusiveFrame',
               'attackRangeType',
               'blackboard',
               'buffInputBase',
               'buffs',
               'canCastInAir',
               'canCastInWater',
               'canDummyCast',
               'canMove',
               'cardAttributeModifier',
               'castData',
               'castType',
               'characterReturnToIdle',
               'comboSkillUIBigSpriteName',
               'comboSkillUISpriteName',
               'dontInterruptCombo',
               'dummyPositionOffset',
               'durationFrame',
               'exclusiveFrame',
               'hittableAttackRange',
               'iconBgType',
               'iconId',
               'level',
               'needEnemyOutOfScreenWarning',
               'needEnemyOutOfScreenWarningOverrideValue',
               'offsetRecordFrame',
               'overrideHittableObjAttackRange',
               'overrideNeedEnemyOutOfScreenWarning',
               'passiveSkillType',
               'rootMotionCliffCheck',
               'selectStrategy',
               'showNotRecommendState',
               'skillHighlightCondition',
               'skillId',
               'skillName',
               'skillSpecification',
               'skillTags',
               'smartTargetBuffFindSettings',
               'smartTargetBuffIds',
               'smartTargetSelectStrategy',
               'smartTargetTagQuery',
               'switchToBuffConfig',
               'switchToCenterBeforeCast',
               'tagDuringAttach',
               'toggleBuffs',
               'uiRangeHints',
               'useAIExclusiveFrame']}
