"""Managed audio literals and fingerprint-locked native consumers."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

from . import context_utils, identifiers, native_evidence


NATIVE_STRING_EVENT_PLAYBACK = {
    "playbackCall": "nativeStringEventWrapper", "playbackCallVa": "0x183287c90",
    "playbackParameter": "eventName",
    "playbackHashCall": "Beyond.Audio.AudioHashGenerator.Compute", "playbackHashCallVa": "0x18328dcd0",
    "playbackSink": "Beyond.Audio.AudioAdapter._PostEvent", "playbackSinkVa": "0x18328a690",
}
NATIVE_STRING_EVENT_FORWARDER_PLAYBACK = {
    "playbackCall": "nativeStringEventForwarder", "playbackCallVa": "0x183d3f2e0",
    "playbackParameter": "eventName",
    "playbackHashCall": "Beyond.Audio.AudioHashGenerator.Compute", "playbackHashCallVa": "0x18328dcd0",
    "playbackSink": "Beyond.Audio.AudioAdapter._PostEvent", "playbackSinkVa": "0x18328a690",
}
NATIVE_POSITION_EVENT_PLAYBACK = {
    "playbackCall": "nativeStringPositionEventWrapper", "playbackCallVa": "0x183b87ba0",
    "playbackParameter": "eventNameAndWorldPosition",
    "playbackHashCall": "Beyond.Audio.AudioHashGenerator.Compute", "playbackHashCallVa": "0x18328dcd0",
    "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PlaySoundAtPosition", "playbackSinkVa": "0x183b87c60",
}
NATIVE_MOBILE_MOTION_EVENT_PLAYBACK = {
    "playbackCall": "mobileMotionConditionalEventWrapper", "playbackCallVa": "0x18b0f5f68",
    "playbackParameter": "motionManagerAndEventName",
    "playbackHashCall": "Beyond.Audio.AudioHashGenerator.Compute", "playbackHashCallVa": "0x18328dcd0",
    "playbackSink": "Beyond.Audio.AudioAdapter._PostEvent", "playbackSinkVa": "0x18328a690",
}
NATIVE_AUDIO_OBJECT_STRING_EVENT_PLAYBACK = {
    "playbackCall": "nativeAudioObjectStringEventWrapper", "playbackCallVa": "0x1847d90c0",
    "playbackParameter": "audioObject,eventName",
    "playbackHashCall": "Beyond.Audio.AudioHashGenerator.Compute", "playbackHashCallVa": "0x18328dcd0",
    "playbackHashInvocationVa": "0x183b878df",
    "playbackSink": "Beyond.Audio.AudioAdapter._PostEvent", "playbackSinkVa": "0x18328a690",
    "playbackSinkInvocationVa": "0x183b878f9",
}
NARRATIVE_3D_RADIO_SELECTOR_ROWS = (
    (2, "020", "0x1852edb10"),
    (4, "040", "0x1852edb28"),
    (5, "050", "0x1852edb40"),
    (6, "060", "0x1852edb58"),
    (7, "070", "0x1852edb70"),
    (8, "080", "0x1852edb88"),
    (10, "100", "0x1852edba0"),
    (12, "120", "0x1852edbb8"),
    (16, "160", "0x1852edbd0"),
    (20, "200", "0x1852edbe8"),
)
NATURE_RESOURCE_SOUND_SELECTOR_ROWS = (
    ("plow", "Reclaim", 1, "0x183b16e14", "0x183b16e9f"),
    ("watering", "Watering", 2, "0x183b16e2f", "0x183b16eba"),
    ("harvest", "Harvest", 5, "0x183b16e4a", "0x183b16ed5"),
)
SELECTOR_AUDIO_CALLSITE_CONTEXTS = {
    "au_ui_event_explorelevels_hold": {
        "consumerType": "Beyond.UI.UISemiCircleScrollList", "consumerMethod": "OnBeginDrag",
        "methodIndex": 400238, "methodVa": "0x18b0f3910",
        "selectorType": "Beyond.UI.UISemiCircleScrollList", "selectorMethod": "_audioHoldStart",
        "selectorField": "_audioHoldStart", "selectorFieldOffset": "this+0xf8", "selectorLoadVa": "0x18b0f3930",
        "literalLoadVa": "0x18b0f4721", "literalArgumentRegister": "rax",
        "literalArgumentInstruction": "audioIdFieldLoad",
        "playbackCall": "Beyond.Audio.AudioUIUtil.PostUIEvent", "playbackCallVa": "0x18b0f3958",
        "playbackParameter": "audioId,gameObject", "targetBinding": "semiCircleScrollListGameObject",
        "triggerRole": "exploreLevelsDragHoldStart",
        "branchCondition": "OnBeginDrag && _audioHoldStart is non-empty",
    },
    "au_ui_event_explorelevels_release": {
        "consumerType": "Beyond.UI.UISemiCircleScrollList", "consumerMethod": "OnEndDrag",
        "methodIndex": 400239, "methodVa": "0x18b0f3b50",
        "selectorType": "Beyond.UI.UISemiCircleScrollList", "selectorMethod": "_audioHoldEnd",
        "selectorField": "_audioHoldEnd", "selectorFieldOffset": "this+0x100", "selectorLoadVa": "0x18b0f3b74",
        "literalLoadVa": "0x18b0f4734", "literalArgumentRegister": "rax",
        "literalArgumentInstruction": "audioIdFieldLoad",
        "playbackCall": "Beyond.Audio.AudioUIUtil.PostUIEvent", "playbackCallVa": "0x18b0f3b9c",
        "playbackParameter": "audioId,gameObject", "targetBinding": "semiCircleScrollListGameObject",
        "triggerRole": "exploreLevelsDragRelease",
        "branchCondition": "OnEndDrag && _audioHoldEnd is non-empty, before damping starts",
    },
    "au_ui_event_explorelevels_alignment": {
        "consumerType": "Beyond.UI.UISemiCircleScrollList+<_ApplyDamping>d__46", "consumerMethod": "MoveNext",
        "methodIndex": 400248, "methodVa": "0x18b0ee2a0",
        "selectorType": "Beyond.UI.UISemiCircleScrollList", "selectorMethod": "_audioAlignment",
        "selectorField": "_audioAlignment", "selectorFieldOffset": "owner+0x108", "selectorLoadVa": "0x18b0ee569",
        "literalLoadVa": "0x18b0f474e", "literalArgumentRegister": "rax",
        "literalArgumentInstruction": "audioIdFieldLoad",
        "playbackCall": "Beyond.Audio.AudioUIUtil.PostUIEvent", "playbackCallVa": "0x18b0ee591",
        "playbackParameter": "audioId,gameObject", "targetBinding": "semiCircleScrollListGameObject",
        "triggerRole": "exploreLevelsScrollAlignment",
        "branchCondition": "_ApplyDamping completes final aligned layout && _audioAlignment is non-empty",
    },
    "au_ui_event_explorelevels_set": {
        "consumerType": "Beyond.UI.UIWorldLevelScrollListAnimCtrl+<_ScrollLayouts>d__12", "consumerMethod": "MoveNext",
        "methodIndex": 400599, "methodVa": "0x18b0f8414",
        "selectorType": "Beyond.UI.UIWorldLevelScrollListAnimCtrl", "selectorMethod": "_audioEnd",
        "selectorField": "_audioEnd", "selectorFieldOffset": "owner+0x40", "selectorLoadVa": "0x18b0f8ad3",
        "literalLoadVa": "0x18b0fe125", "literalArgumentRegister": "rax",
        "literalArgumentInstruction": "audioIdFieldLoad",
        "playbackCall": "Beyond.Audio.AudioUIUtil.PostUIEvent", "playbackCallVa": "0x18b0f8af8",
        "playbackParameter": "audioId,gameObject", "targetBinding": "worldLevelScrollListAnimControllerGameObject",
        "triggerRole": "exploreLevelsSetCompleted",
        "branchCondition": "_ScrollLayouts completes final local-position updates && _audioEnd is non-empty",
    },
    "au_int_xiranitenexus_appear": {
        "consumerType": "Beyond.Gameplay.XiraniteNexusLogicComponent", "consumerMethod": "NotifyShown",
        "methodIndex": 7571, "methodVa": "0x186ff8644",
        "selectorType": "Beyond.Gameplay.XiraniteNexusConfig", "selectorMethod": "appearAudio",
        "selectorField": "appearAudio", "selectorFieldOffset": "config+0x100", "selectorLoadVa": "0x186ff86dd",
        "literalLoadVa": "0x18480ad61", "literalArgumentRegister": "rdx",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.XiraniteNexusLogicComponent._PlayAudio",
        "playbackCallVa": "0x186ff86ea", "playbackParameter": "eventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x186ff9a50",
        "targetBinding": "xiraniteNexusEntityAudioObject", "triggerRole": "xiraniteNexusShown",
        "branchCondition": "NotifyShown && isVisible changes false->true",
    },
    "au_int_xiranitenexus_disappear": {
        "consumerType": "Beyond.Gameplay.XiraniteNexusLogicComponent", "consumerMethod": "NotifyHidden",
        "methodIndex": 7572, "methodVa": "0x186ff8394",
        "selectorType": "Beyond.Gameplay.XiraniteNexusConfig", "selectorMethod": "disappearAudio",
        "selectorField": "disappearAudio", "selectorFieldOffset": "config+0x108", "selectorLoadVa": "0x186ff8420",
        "literalLoadVa": "0x18480ad7b", "literalArgumentRegister": "rdx",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.XiraniteNexusLogicComponent._PlayAudio",
        "playbackCallVa": "0x186ff842d", "playbackParameter": "eventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x186ff9a50",
        "targetBinding": "xiraniteNexusEntityAudioObject", "triggerRole": "xiraniteNexusHidden",
        "branchCondition": "NotifyHidden && isVisible changes true->false",
    },
    "au_int_xiranitenexus_scan_start": {
        "consumerType": "Beyond.Gameplay.XiraniteNexusLogicComponent", "consumerMethod": "OnScanEnable",
        "methodIndex": 7573, "methodVa": "0x186ff9024",
        "selectorType": "Beyond.Gameplay.XiraniteNexusConfig", "selectorMethod": "scanStartAudio",
        "selectorField": "scanStartAudio", "selectorFieldOffset": "config+0x110", "selectorLoadVa": "0x186ff90a7",
        "literalLoadVa": "0x18480ad95", "literalArgumentRegister": "rdx",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.XiraniteNexusLogicComponent._PlayAudio",
        "playbackCallVa": "0x186ff90b4", "playbackParameter": "eventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x186ff9a50",
        "targetBinding": "xiraniteNexusEntityAudioObject", "triggerRole": "xiraniteNexusScanEnabled",
        "branchCondition": "OnScanEnable",
    },
    "au_int_xiranitenexus_scan_end": {
        "consumerType": "Beyond.Gameplay.XiraniteNexusLogicComponent", "consumerMethod": "OnScanDisable",
        "methodIndex": 7574, "methodVa": "0x186ff8cd8",
        "selectorType": "Beyond.Gameplay.XiraniteNexusConfig", "selectorMethod": "scanEndAudio",
        "selectorField": "scanEndAudio", "selectorFieldOffset": "config+0x118", "selectorLoadVa": "0x186ff8d62",
        "literalLoadVa": "0x18480adaf", "literalArgumentRegister": "rdx",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.XiraniteNexusLogicComponent._PlayAudio",
        "playbackCallVa": "0x186ff8d6f", "playbackParameter": "eventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x186ff9a50",
        "targetBinding": "xiraniteNexusEntityAudioObject", "triggerRole": "xiraniteNexusScanDisabled",
        "branchCondition": "OnScanDisable",
    },
    "au_int_xiranitenexus_flash": {
        "consumerType": "Beyond.Gameplay.XiraniteNexusLogicComponent", "consumerMethod": "OnBlightMiasmaAreaEnter",
        "methodIndex": 7576, "methodVa": "0x186ff89ec",
        "selectorType": "Beyond.Gameplay.XiraniteNexusConfig", "selectorMethod": "flashAudio",
        "selectorField": "flashAudio", "selectorFieldOffset": "config+0x120", "selectorLoadVa": "0x186ff8a14",
        "literalLoadVa": "0x18480adc9", "literalArgumentRegister": "rdx",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.XiraniteNexusLogicComponent._PlayAudio",
        "playbackCallVa": "0x186ff8a21", "playbackParameter": "eventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x186ff9a50",
        "additionalConsumerMethod": "OnStart", "additionalMethodVa": "0x186ff92d4",
        "additionalSelectorLoadVa": "0x186ff94ba", "additionalPlaybackCallVa": "0x186ff94c7",
        "targetBinding": "xiraniteNexusEntityAudioObject", "triggerRole": "xiraniteNexusBlightFlash",
        "branchCondition": "blightMiasmaAreaEnter || OnStart while already in blight area",
    },
    "au_int_shuimo_bridge_appear": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.FireSeedBrain", "consumerMethod": "_TickUpdateFireSeedInUse",
        "methodIndex": 82411, "methodVa": "0x183efb0c0",
        "selectorType": "Beyond.Gameplay.Core.GameMech.FireSeedGameplayConfig",
        "selectorMethod": "invisibleBridgeAppearAudio", "selectorField": "invisibleBridgeAppearAudio",
        "selectorFieldOffset": "config+0x98", "selectorLoadVa": "0x183efb825",
        "literalLoadVa": "0x1849bac58", "literalArgumentRegister": "rsi",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x183efb877", "playbackParameter": "eventName",
        "targetBinding": "playerControllerAudioObject", "triggerRole": "invisibleBridgeUseStart",
        "branchCondition": "HasInvisibleBridgeInRange && !wasUsingInvisibleBridge; sets in-use flag true",
        "additionalConsumerMethod": "_PlayFireSeedInUseAudio", "additionalMethodVa": "0x1870d30a0",
        "additionalSelectorLoadVa": "0x1870d30fc", "additionalPlaybackCallVa": "0x1870d313c",
    },
    "au_int_shuimo_bridge_disappear": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.FireSeedBrain", "consumerMethod": "_PlayFireSeedUnUseAudio",
        "methodIndex": 82417, "methodVa": "0x1870d3178",
        "selectorType": "Beyond.Gameplay.Core.GameMech.FireSeedGameplayConfig",
        "selectorMethod": "invisibleBridgeDisappearAudio", "selectorField": "invisibleBridgeDisappearAudio",
        "selectorFieldOffset": "config+0xa0", "selectorLoadVa": "0x1870d31d9",
        "literalLoadVa": "0x1849bac6b", "literalArgumentRegister": "rsi",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1870d3219", "playbackParameter": "eventName",
        "targetBinding": "playerControllerAudioObject", "triggerRole": "invisibleBridgeUseEnd",
        "branchCondition": "invisible bridge leaves range after in-use state, or fire-seed in-use ticking is disabled",
    },
    "au_int_yinglongguan_fire_appear": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.FireSeedBrain", "consumerMethod": "_PlayFireSeedAppearAudio",
        "methodIndex": 82420, "methodVa": "0x1870d2f08",
        "selectorType": "Beyond.Gameplay.Core.GameMech.FireSeedGameplayConfig",
        "selectorMethod": "fireSeedAppearAudio", "selectorField": "fireSeedAppearAudio",
        "selectorFieldOffset": "config+0xa8", "selectorLoadVa": "0x1870d2f5f",
        "literalLoadVa": "0x1849bac85", "literalArgumentRegister": "rsi",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1870d2f9f", "playbackParameter": "eventName",
        "targetBinding": "playerControllerAudioObject", "triggerRole": "fireSeedAppear",
        "branchCondition": "SetFireSeedLevel with active=true and level>0",
    },
    "au_int_yinglongguan_fire_disappear": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.FireSeedBrain", "consumerMethod": "_PlayFireSeedDisappearAudio",
        "methodIndex": 82421, "methodVa": "0x1870d2fd4",
        "selectorType": "Beyond.Gameplay.Core.GameMech.FireSeedGameplayConfig",
        "selectorMethod": "fireSeedDisappearAudio", "selectorField": "fireSeedDisappearAudio",
        "selectorFieldOffset": "config+0xb0", "selectorLoadVa": "0x1870d302b",
        "literalLoadVa": "0x1849bac9f", "literalArgumentRegister": "rsi",
        "literalArgumentInstruction": "configFieldLoad",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1870d306b", "playbackParameter": "eventName",
        "targetBinding": "playerControllerAudioObject", "triggerRole": "fireSeedDisappear",
        "branchCondition": "SetFireSeedLevel with active=false or level<=0",
    },
    "au_int_blightmiasma_idle_light": {
        "consumerType": "Beyond.Gameplay.BlightMiasmaBrain", "consumerMethod": "_PlayMiasmaAreaIdleAudio",
        "methodIndex": 11363, "methodVa": "0x18721ce64",
        "selectorType": "Beyond.Gameplay.BlightMiasmaBrain", "selectorMethod": "_GetMiasmaAreaIdleAudio",
        "selectorMethodIndex": 11362, "selectorMethodVa": "0x18721cbb0", "selectorCallVa": "0x18721ce9d",
        "literalLoadVa": "0x18721cc2a", "literalArgumentRegister": "rax", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.BlightMiasmaBrain._PlayMiasmaAudio",
        "playbackCallVa": "0x18721ceb6", "playbackParameter": "selectedEventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x18721cf6a",
        "targetBinding": "mainCharacterAudioObject", "triggerRole": "miasmaAreaIdleLight",
        "branchCondition": "miasmaAreaLevel==1",
    },
    "au_int_blightmiasma_idle_medium": {
        "consumerType": "Beyond.Gameplay.BlightMiasmaBrain", "consumerMethod": "_PlayMiasmaAreaIdleAudio",
        "methodIndex": 11363, "methodVa": "0x18721ce64",
        "selectorType": "Beyond.Gameplay.BlightMiasmaBrain", "selectorMethod": "_GetMiasmaAreaIdleAudio",
        "selectorMethodIndex": 11362, "selectorMethodVa": "0x18721cbb0", "selectorCallVa": "0x18721ce9d",
        "literalLoadVa": "0x18721cc21", "literalArgumentRegister": "rax", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.BlightMiasmaBrain._PlayMiasmaAudio",
        "playbackCallVa": "0x18721ceb6", "playbackParameter": "selectedEventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x18721cf6a",
        "targetBinding": "mainCharacterAudioObject", "triggerRole": "miasmaAreaIdleMedium",
        "branchCondition": "miasmaAreaLevel==2",
    },
    "au_int_blightmiasma_idle_heavy": {
        "consumerType": "Beyond.Gameplay.BlightMiasmaBrain", "consumerMethod": "_PlayMiasmaAreaIdleAudio",
        "methodIndex": 11363, "methodVa": "0x18721ce64",
        "selectorType": "Beyond.Gameplay.BlightMiasmaBrain", "selectorMethod": "_GetMiasmaAreaIdleAudio",
        "selectorMethodIndex": 11362, "selectorMethodVa": "0x18721cbb0", "selectorCallVa": "0x18721ce9d",
        "literalLoadVa": "0x18721cc18", "literalArgumentRegister": "rax", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.BlightMiasmaBrain._PlayMiasmaAudio",
        "playbackCallVa": "0x18721ceb6", "playbackParameter": "selectedEventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x18721cf6a",
        "targetBinding": "mainCharacterAudioObject", "triggerRole": "miasmaAreaIdleHeavy",
        "branchCondition": "miasmaAreaLevel==3",
    },
    "au_int_erosion_sludge_idle_loop": {
        "consumerType": "Beyond.Gameplay.Core.ErosionSludgeV2", "consumerMethod": "_PlayAudio",
        "methodIndex": 72093, "methodVa": "0x183aff8e0",
        "selectorType": "Beyond.Gameplay.Core.ErosionSludgeV2", "selectorMethod": "_GetAudioType",
        "selectorMethodIndex": 72096, "selectorMethodVa": "0x183aff9f0", "selectorCallVa": "0x183aff96c",
        "literalLoadVa": "0x183affa2e", "literalArgumentRegister": "rax", "literalArgumentInstruction": "mov",
        **NATIVE_AUDIO_OBJECT_STRING_EVENT_PLAYBACK,
        "playbackInvocationVa": "0x183aff991",
        "targetBinding": "erosionSludgeAudioEmitter", "triggerRole": "erosionSludgeIdleLoop",
        "branchCondition": "audioType==1",
    },
    "au_int_erosion_sludge_recover_loop": {
        "consumerType": "Beyond.Gameplay.Core.ErosionSludgeV2", "consumerMethod": "_PlayRecoverAudio",
        "methodIndex": 72099, "methodVa": "0x186f7037c",
        "selectorType": "Beyond.Gameplay.Core.ErosionSludgeV2", "selectorMethod": "_GetAudioType",
        "selectorMethodIndex": 72096, "selectorMethodVa": "0x183aff9f0", "selectorCallVa": "0x186f70584",
        "literalLoadVa": "0x1851865b3", "literalArgumentRegister": "rax", "literalArgumentInstruction": "mov",
        **NATIVE_AUDIO_OBJECT_STRING_EVENT_PLAYBACK,
        "playbackInvocationVa": "0x186f705a5",
        "targetBinding": "erosionSludgeAudioEmitter", "triggerRole": "erosionSludgeRecoverLoop",
        "branchCondition": "audioType==2",
    },
    "au_int_erosion_sludge_recover_done": {
        "consumerType": "Beyond.Gameplay.Core.ErosionSludgeV2", "consumerMethod": "_PlayRecoverAudio",
        "methodIndex": 72099, "methodVa": "0x186f7037c",
        "selectorType": "Beyond.Gameplay.Core.ErosionSludgeV2", "selectorMethod": "_GetAudioType",
        "selectorMethodIndex": 72096, "selectorMethodVa": "0x183aff9f0", "selectorCallVa": "0x186f70584",
        "literalLoadVa": "0x1851865a7", "literalArgumentRegister": "rax", "literalArgumentInstruction": "mov",
        **NATIVE_AUDIO_OBJECT_STRING_EVENT_PLAYBACK,
        "playbackInvocationVa": "0x186f705a5",
        "targetBinding": "erosionSludgeAudioEmitter", "triggerRole": "erosionSludgeRecoverDone",
        "branchCondition": "audioType==3",
    },
    **{
        f"au_voice_narrating_3dradio_{suffix}": {
            "consumerType": "Beyond.Gameplay.Audio.VoiceManager", "consumerMethod": "_SpeakNarrative",
            "methodIndex": 40555, "methodVa": "0x1845e3f20",
            "selectorType": "Beyond.Gameplay.Audio.NarrativeVoiceConfig",
            "selectorMethod": "SetSpecialOverrideWwiseEvent", "selectorMethodIndex": 40485,
            "selectorMethodVa": "0x1845e4460", "selectorCallVa": "0x1845e4177",
            "literalLoadVa": load_va, "literalArgumentRegister": "rax", "literalArgumentInstruction": "mov",
            "playbackCall": "Beyond.Gameplay.Audio.VoicePlayer.PlayVoice",
            "playbackCallVa": "0x1845e4196", "playbackParameter": "voiceContext.selectedWwiseEvent",
            "targetBinding": "narrativeVoiceContext", "triggerRole": "narrative3DRadioOverride",
            "branchCondition": f"specialOverrideWwiseEvent=={selector_value}",
        }
        for selector_value, suffix, load_va in NARRATIVE_3D_RADIO_SELECTOR_ROWS
    },
    **{
        f"au_int_farming_{event_stem}_start": {
            "consumerType": "Beyond.Gameplay.NatureResourceManager", "consumerMethod": "DoOperation",
            "methodIndex": 12869, "methodVa": "0x18726a090",
            "selectorType": "Beyond.Gameplay.NatureResourceManager",
            "selectorMethod": "m_startSoundMap.TryGetValue", "selectorField": "m_startSoundMap",
            "selectorFieldOffset": "this+0xd0", "selectorCallVa": "0x18726a2dc",
            "literalLoadVa": start_load_va, "literalArgumentRegister": "rdx",
            "literalArgumentInstruction": "dictionaryLookup",
            "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
            "playbackCallVa": "0x18726a30e", "playbackParameter": "evt",
            "targetBinding": "natureOperationActorAudioObject", "triggerRole": f"natureOperation{enum_name}Start",
            "branchCondition": f"operationType==ENatureOperation.{enum_name}({enum_value})",
        }
        for event_stem, enum_name, enum_value, start_load_va, _ in NATURE_RESOURCE_SOUND_SELECTOR_ROWS
    },
    **{
        f"au_int_farming_{event_stem}_end": {
            "consumerType": "Beyond.Gameplay.NatureResourceManager", "consumerMethod": "OperationFinish",
            "methodIndex": 12876, "methodVa": "0x18726b190",
            "selectorType": "Beyond.Gameplay.NatureResourceManager",
            "selectorMethod": "m_endSoundMap.TryGetValue", "selectorField": "m_endSoundMap",
            "selectorFieldOffset": "this+0xd8", "selectorCallVa": "0x18726b56c",
            "literalLoadVa": end_load_va, "literalArgumentRegister": "rdx",
            "literalArgumentInstruction": "dictionaryLookup",
            "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
            "playbackCallVa": "0x18726b59e", "playbackParameter": "evt",
            "additionalConsumerMethod": "_FinishOperation", "additionalMethodVa": "0x18726c218",
            "additionalSelectorCallVa": "0x18726c383", "additionalPlaybackCallVa": "0x18726c3b5",
            "targetBinding": "natureResourceEntityAudioObject", "triggerRole": f"natureOperation{enum_name}End",
            "branchCondition": f"operationType==ENatureOperation.{enum_name}({enum_value})",
        }
        for event_stem, enum_name, enum_value, _, end_load_va in NATURE_RESOURCE_SOUND_SELECTOR_ROWS
    },
}
MANAGED_AUDIO_CALLSITE_CONTEXTS = {
    **SELECTOR_AUDIO_CALLSITE_CONTEXTS,
    "au_ui_event_socialbuildinglike": {
        "consumerType": "Beyond.Gameplay.Factory.FactorySocialBuildingCircleEffectCtrl",
        "consumerMethod": "_UpdateBuildingSocialState", "methodIndex": 26304,
        "methodVa": "0x18408b270", "literalLoadVa": "0x185255f2c",
        "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        "playbackCall": "nativeStringPositionEventWrapper", "playbackCallVa": "0x185255f42",
        "playbackParameter": "eventNameAndWorldPosition",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PlaySoundAtPosition",
        "playbackSinkVa": "0x183b87c60", "targetBinding": "socialBuildingControllerTransformPosition",
        "triggerRole": "socialBuildingLikeStateChanged",
        "branchCondition": "updated social state==3 && socialUnit value changed",
    },
    "au_ui_popup_levelup_ingame_side": {
        "consumerType": "Beyond.UI.SquadIcon", "consumerMethod": "_TryShowLevelUpAnim",
        "methodIndex": 425791, "methodVa": "0x184665560", "literalLoadVa": "0x1852fc2eb",
        "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "playbackInvocationVa": "0x1852fc2f2", "targetBinding": "globalAudioObject",
        "triggerRole": "squadIconLevelUpAnimation",
        "branchCondition": "current level exceeds cached level && component enabled; after PlayInAnimation starts",
    },
    "au_weekraid_danger_warnning_start": {
        "consumerType": "Beyond.Gameplay.Core.WeekRaidGame",
        "consumerMethod": "_PlayDangerEffectOnMainCharacter", "methodIndex": 71625,
        "methodVa": "0x186f600f4", "literalLoadVa": "0x186f6041a",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.Core.WeekRaidGame", "selectorMethod": "s_DangerAudio",
        "selectorField": "s_DangerAudio", "selectorFieldOffset": "static+0x10",
        "selectorLoadVa": "0x186f60312",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186f60333", "playbackParameter": "gameObject,audioId",
        "targetBinding": "mainCharacterModelGameObject", "triggerRole": "weekRaidDangerThresholdCrossed",
        "branchCondition": "UpdateDangerMeter level==1 && current meter rose above previous meter",
    },
    "au_int_collection_intteractive": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicCollectionMoon",
        "consumerMethod": "_OnCollect", "methodIndex": 9058, "methodVa": "0x187141588",
        "literalLoadVa": "0x1871418d8", "literalArgumentRegister": "rdi",
        "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.InteractiveLogicCollectionMoon", "selectorMethod": "AUDIO_COLLECT",
        "selectorField": "AUDIO_COLLECT", "selectorFieldOffset": "static+0x8",
        "selectorLoadVa": "0x18714164f",
        "playbackCall": "nativeStringPositionEventWrapper", "playbackCallVa": "0x1871416aa",
        "playbackParameter": "eventNameAndWorldPosition",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PlaySoundAtPosition",
        "playbackSinkVa": "0x183b87c60", "targetBinding": "collectionMoonEntityPosition",
        "triggerRole": "collectionMoonCollected",
        "branchCondition": "_OnPropertyChangedState invokes _OnCollect; after collected animator flag is set",
    },
    "au_int_collection_coin_countingdown": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicCollectionCoin",
        "consumerMethod": "_PlayDisappearPerform", "methodIndex": 9029,
        "methodVa": "0x187140d58", "literalLoadVa": "0x187141252",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.InteractiveLogicCollectionCoin",
        "selectorMethod": "DISAPPEAR_AUDIO_NAME", "selectorField": "DISAPPEAR_AUDIO_NAME",
        "selectorFieldOffset": "static+0x40", "selectorLoadVa": "0x187140f4e",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x187140f6f", "playbackParameter": "entity,audioId",
        "additionalConsumerType": "Beyond.Gameplay.Core.InteractiveCollectionCoinComponent",
        "additionalConsumerMethod": "_PlayDisappearPerform", "additionalMethodIndex": 67467,
        "additionalMethodVa": "0x186eceff4", "additionalLiteralLoadVa": "0x184b88632",
        "additionalSelectorFieldOffset": "static+0x8", "additionalSelectorLoadVa": "0x186ecf1d3",
        "additionalPlaybackCallVa": "0x186ecf1f4",
        "targetBinding": "collectionCoinEntity", "triggerRole": "collectionCoinDisappearCountdown",
        "branchCondition": "_PlayDisappearPerform after disappear effect creation and countdown duration initialization",
    },
    "au_int_gold_coin_eny_die": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.InteractiveGoldCoinBrain",
        "consumerMethod": "_PlayCreateCoinAudio", "methodIndex": 82819,
        "methodVa": "0x1870e0f6c", "literalLoadVa": "0x184a3f5c9",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.Core.GameMech.InteractiveGoldCoinBrain",
        "selectorMethod": "AUDIO_ENEMY_DIE", "selectorField": "AUDIO_ENEMY_DIE",
        "selectorFieldOffset": "static+0x28", "selectorLoadVa": "0x1870e0fd6",
        "playbackCall": "Beyond.Gameplay.Actions.GameAction.PlayAudioAtPosition",
        "playbackCallVa": "0x1870e1002", "playbackParameter": "audioId,position",
        "callerMethod": "AddGoldCoin", "callerMethodIndex": 82818,
        "callerMethodVa": "0x1870ddc34", "callerCallVa": "0x1870de140",
        "targetBinding": "goldCoinCreationPosition", "triggerRole": "monsterSourceGoldCoinCreated",
        "branchCondition": "source==EGoldCoinSource.Monster(3)",
    },
    "au_int_gold_coin_eny_trigger": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.InteractiveGoldCoinBrain",
        "consumerMethod": "_PlayGoldCoinDisappearAudio", "methodIndex": 82811,
        "methodVa": "0x1870e1050", "literalLoadVa": "0x184a3f54e",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.Core.GameMech.InteractiveGoldCoinBrain",
        "selectorMethod": "AUDIO_COIN_DISAPPEAR", "selectorField": "AUDIO_COIN_DISAPPEAR",
        "selectorFieldOffset": "static+0x20", "selectorLoadVa": "0x1870e10b1",
        "playbackCall": "Beyond.Gameplay.Actions.GameAction.PlayAudioAtPosition",
        "playbackCallVa": "0x1870e10dd", "playbackParameter": "audioId,position",
        "callerMethod": "PlayCoinExplodeEffect", "callerMethodIndex": 82810,
        "callerMethodVa": "0x1870deaf8", "callerCallVa": "0x1870decb2",
        "targetBinding": "playerPositionPlusGoldCoinEffectOffset",
        "triggerRole": "goldCoinExplodeDisappear",
        "branchCondition": "PlayCoinExplodeEffect after the player-relative effect position is calculated",
    },
    "au_sfx_enemy_drop_absorbing_02": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.FlyThread",
        "consumerMethod": "_PlayDisappearAudio", "methodIndex": 82965,
        "methodVa": "0x183b94370", "literalLoadVa": "0x184d128c9",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.Core.GameMech.FlyThread",
        "selectorMethod": "DROP_EFFECT_FIRST", "selectorField": "DROP_EFFECT_FIRST",
        "selectorFieldOffset": "static+0x0", "selectorLoadVa": "0x183b9444e",
        "playbackCall": "nativeStringPositionEventWrapper", "playbackCallVa": "0x183b944cc",
        "playbackParameter": "eventNameAndWorldPosition",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PlaySoundAtPosition",
        "playbackSinkVa": "0x183b87c60",
        "callerMethod": "_Finish", "callerMethodIndex": 82964,
        "callerMethodVa": "0x1870e4f98", "callerCallVa": "0x1870e50cd",
        "targetBinding": "flyThreadTargetEntityPositionPlusFinishEffectYOffset",
        "triggerRole": "enemyDropAbsorptionFinish",
        "branchCondition": "_Finish after absorb effect creation; _PlayDisappearAudio cooldown permits playback",
    },
    "au_sfx_enemy_drop_absorbing_01_start": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.FlyThread",
        "consumerMethod": "_PlayDisappearAudio", "methodIndex": 82965,
        "methodVa": "0x183b94370", "literalLoadVa": "0x184d128d5",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.Core.GameMech.FlyThread",
        "selectorMethod": "DROP_EFFECT_SECOND", "selectorField": "DROP_EFFECT_SECOND",
        "selectorFieldOffset": "static+0x8", "selectorLoadVa": "0x183b94523",
        "playbackCall": "nativeStringPositionEventWrapper", "playbackCallVa": "0x183b944cc",
        "playbackParameter": "eventNameAndWorldPosition",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PlaySoundAtPosition",
        "playbackSinkVa": "0x183b87c60",
        "callerMethod": "_Finish", "callerMethodIndex": 82964,
        "callerMethodVa": "0x1870e4f98", "callerCallVa": "0x1870e50cd",
        "targetBinding": "flyThreadTargetEntityPositionPlusFinishEffectYOffset",
        "triggerRole": "repeatedEnemyDropAbsorptionFinish",
        "branchCondition": "_PlayDisappearAudio selects DROP_EFFECT_SECOND while nextRefreshTime is set and current time remains before it",
    },
    "au_int_medicalstation_end": {
        "consumerType": "Beyond.Gameplay.RemoteFactory.RemoteFactoryMedicalTowerManager",
        "consumerMethod": "_DoTick", "methodIndex": 29572,
        "methodVa": "0x18376c7c0", "literalLoadVa": "0x1850f5db7",
        "literalArgumentRegister": "rdx", "literalArgumentInstruction": "coldBranchManagedLiteralLoad",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1850f5dd1", "playbackParameter": "entity,audioId",
        "targetBinding": "medicalTowerEntity", "triggerRole": "mainCharacterExitedMedicalTowerRange",
        "branchCondition": "the previous range tower no longer contains the main character; after MedicFunctionManager.ClearRangeTower",
    },
    "au_int_medicalstation_start": {
        "consumerType": "Beyond.Gameplay.RemoteFactory.RemoteFactoryMedicalTowerManager",
        "consumerMethod": "_DoTick", "methodIndex": 29572,
        "methodVa": "0x18376c7c0", "literalLoadVa": "0x1850f5e4e",
        "literalArgumentRegister": "rdx", "literalArgumentInstruction": "coldBranchManagedLiteralLoad",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1850f5e68", "playbackParameter": "entity,audioId",
        "targetBinding": "medicalTowerEntity", "triggerRole": "mainCharacterEnteredMedicalTowerRange",
        "branchCondition": "the nearest medical tower contains the main character; after MedicFunctionManager.SetRangeTower",
    },
    "au_ui_hud_tacticalmedicationrecovery": {
        "consumerType": "Beyond.UI.SquadIcon",
        "consumerMethod": "_UpdateTacticalItemStatus", "methodIndex": 425800,
        "methodVa": "0x18339ff90", "literalLoadVa": "0x18504f14d",
        "literalArgumentRegister": "rcx", "literalArgumentInstruction": "coldBranchManagedLiteralLoad",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "playbackInvocationVa": "0x18504f154",
        "targetBinding": "globalAudioObject", "triggerRole": "tacticalMedicationChargeRecovered",
        "branchCondition": "the squad is in combat and current usable tactical-item count exceeds the cached count; after the recovery tween starts",
    },
    "au_eny_find_target": {
        "consumerType": "Beyond.Gameplay.AI.EnemyBattleGraph",
        "consumerMethod": "OnEnter", "methodIndex": 43420,
        "methodVa": "0x184134080", "literalLoadVa": "0x184b4a93d",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "configuredAudioNameFieldLoad",
        "selectorType": "Beyond.Gameplay.AI.EnemyBattleGraph+EnemyBattleGraphData",
        "selectorMethod": "soundName", "selectorField": "soundName",
        "selectorFieldOffset": "graphData+0x38", "selectorLoadVa": "0x1841357ab",
        "playbackCall": "nativeStringPositionEventWrapper", "playbackCallVa": "0x1841357f9",
        "playbackParameter": "eventNameAndWorldPosition",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PlaySoundAtPosition",
        "playbackSinkVa": "0x183b87c60",
        "targetBinding": "enemyBattleGraphEntityPosition", "triggerRole": "enemyBattleGraphEntered",
        "branchCondition": "EnemyBattleGraph.OnEnter after graph state is initialized; soundName defaults to au_eny_find_target",
    },
    "au_int_farming_addsoil": {
        "consumerType": "Beyond.Gameplay.FacSoilSystem",
        "consumerMethod": "OnNodeAdded", "methodIndex": 16905,
        "methodVa": "0x1838fe9f0", "literalLoadVa": "0x1851390a1",
        "literalArgumentRegister": "rdx", "literalArgumentInstruction": "coldBranchManagedLiteralLoad",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1851390bd", "playbackParameter": "entity,audioId",
        "targetBinding": "mainCharacterEntity", "triggerRole": "factorySoilNodeAdded",
        "branchCondition": "the chapter node resolves as a soil node and FacSoilSystem.AddSoilNode completes",
    },
    "au_int_anchor_wave_explosion": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore",
        "consumerMethod": "_DoWaveVFX", "methodIndex": 8698,
        "methodVa": "0x1870b9270", "literalLoadVa": "0x1870bebb9",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore",
        "selectorMethod": "ANCHOR_EXPLOSION_AUDIO", "selectorField": "ANCHOR_EXPLOSION_AUDIO",
        "selectorFieldOffset": "static+0x10", "selectorLoadVa": "0x1870b93c4",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1870b93ec", "playbackParameter": "entity,audioId",
        "targetBinding": "anchorWaveCoreEntity", "triggerRole": "anchorWaveExplosion",
        "branchCondition": "_DoWaveVFX after creating the wave effect at the anchor entity position",
    },
    "au_int_anchor_wave_diffusion": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore",
        "consumerMethod": "_DoWaveVFX", "methodIndex": 8698,
        "methodVa": "0x1870b9270", "literalLoadVa": "0x1870bebd1",
        "literalArgumentRegister": "rdx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore",
        "selectorMethod": "ANCHOR_WAVE_SPREAD_AUDIO", "selectorField": "ANCHOR_WAVE_SPREAD_AUDIO",
        "selectorFieldOffset": "static+0x18", "selectorLoadVa": "0x1870b941e",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1870b9422", "playbackParameter": "entity,audioId",
        "targetBinding": "anchorWaveCoreEntity", "triggerRole": "anchorWaveSpread",
        "branchCondition": "_DoWaveVFX immediately after the anchor explosion Event",
    },
    "au_int_anchor_idle": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicSimpleAnchorWaveCore",
        "consumerMethod": "_HideSceneDynamicObjectEffectWithCondition", "methodIndex": 10210,
        "methodVa": "0x187203704", "literalLoadVa": "0x187204d89",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.InteractiveLogicSimpleAnchorWaveCore",
        "selectorMethod": "ANCHOR_IDLE_AUDIO", "selectorField": "ANCHOR_IDLE_AUDIO",
        "selectorFieldOffset": "static+0x0", "selectorLoadVa": "0x18720380c",
        "playbackCall": "Beyond.Gameplay.Core.DynamicScene.DynamicSceneConditionHelper.PlayLoopAudioIfNecessary",
        "playbackCallVa": "0x18720381d", "playbackParameter": "sceneDynamicMono,audioId",
        "targetBinding": "anchorSceneDynamicMono", "triggerRole": "anchorIdleLoopRestore",
        "branchCondition": "anchor state is idle and scene dynamic object effect is being restored",
    },
    "au_env_npc_butterflyclust_small_interactall": {
        "consumerType": "Beyond.Gameplay.Core.GuideButterflyModuleController",
        "consumerMethod": "_OnSmallButterflyCollected", "methodIndex": 73832,
        "methodVa": "0x186f9ec3c", "literalLoadVa": "0x184d50759",
        "literalArgumentRegister": "rbx", "literalArgumentInstruction": "staticAudioIdFieldLoad",
        "selectorType": "Beyond.Gameplay.Core.GuideButterflyModuleController",
        "selectorMethod": "ALL_SMALL_BUTTER_FLY_COLLECTED_AUDIO",
        "selectorField": "ALL_SMALL_BUTTER_FLY_COLLECTED_AUDIO",
        "selectorFieldOffset": "static+0x0", "selectorLoadVa": "0x186f9edaf",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186f9ee02", "playbackParameter": "entity,audioId",
        "additionalPlaybackCall": "nativeStringEventWrapper",
        "additionalPlaybackCallVa": "0x186f9edc1",
        "targetBinding": "collectedSmallButterflyEntityWhenResolvedOtherwiseGlobal",
        "triggerRole": "allSmallGuideButterfliesCollected",
        "branchCondition": "the pending small-butterfly id set becomes empty after collection",
    },
    "au_gameplay_common_scanning_feedback_lv1": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.TreasureHuntBrain",
        "consumerMethod": "OnTriggerScanInteractive",
        "methodIndex": 83368,
        "methodVa": "0x18710e248",
        "literalLoadVa": "0x18710e81e",
        "playbackCall": "Beyond.Gameplay.Actions.GameAction.PlayAudio",
        "playbackCallVa": "0x18710e773",
        "targetBinding": "scannedInteractiveModelGameObject",
        "triggerRole": "scanFeedbackLevel1",
    },
    "au_int_campfire_recover": {
        "consumerType": "Beyond.Gameplay.Core.InteractiveCampfireComponent",
        "consumerMethod": "_LocalReqRecovery",
        "methodIndex": 67409,
        "methodVa": "0x186ecd03c",
        "literalLoadVa": "0x186ecd141",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186ecd15d",
        "targetBinding": "componentAudioObject",
        "triggerRole": "localRecoveryRequest",
    },
    "au_int_box_collision": {
        "consumerType": "Beyond.Gameplay.Core.PushableComponent",
        "consumerMethod": "_InternalUpdateAttached",
        "methodIndex": 69383,
        "methodVa": "0x186f10b18",
        "literalLoadVa": "0x186f10c07",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186f10c11",
        "targetBinding": "componentAudioObject",
        "triggerRole": "attachedCollisionUpdate",
    },
    "au_ui_button_hyperlink": {
        "consumerType": "Beyond.UI.UIText", "consumerMethod": "OnPointerClick",
        "methodIndex": 397877, "methodVa": "0x18b08c134",
        "literalLoadVa": "0x18b08c2e1", "literalArgumentRegister": "rcx",
        "playbackCall": "Beyond.Audio.AudioUIUtil.PostUIEvent",
        "playbackCallVa": "0x18b08c2e8", "playbackParameter": "eventName",
        "targetBinding": "clickedUiGameObject", "triggerRole": "hyperlinkClick",
    },
    "au_ui_event_growcabin_finish": {
        "consumerType": "Beyond.Gameplay.SpaceshipGrowCabinViewHandler", "consumerMethod": "_PlayGrowFinishAudio",
        "methodIndex": 12126, "methodVa": "0x187252d68",
        "literalLoadVa": "0x187252dbf", "literalArgumentRegister": "r8",
        "playbackCall": "Beyond.Gameplay.Core.DynamicScene.DynamicSceneConditionHelper.PlaySoundAtPlantPos",
        "playbackCallVa": "0x187252dce", "playbackParameter": "soundEventName",
        "targetBinding": "cabinPlantPosition", "triggerRole": "growCabinFinish",
    },
    "au_gameplay_common_scanning_feedback_lv2": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.TreasureHuntBrain", "consumerMethod": "OnTriggerScanInteractive",
        "methodIndex": 83368, "methodVa": "0x18710e248",
        "literalLoadVa": "0x18710e7f0", "literalArgumentRegister": "rcx",
        "playbackCall": "Beyond.Gameplay.Actions.GameAction.PlayAudio",
        "playbackCallVa": "0x18710e773", "playbackParameter": "audioEventKey",
        "targetBinding": "scannedInteractiveModelGameObject", "triggerRole": "scanFeedbackLevel2",
    },
    "au_gameplay_common_scanning_feedback_lv3": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.TreasureHuntBrain", "consumerMethod": "OnTriggerScanInteractive",
        "methodIndex": 83368, "methodVa": "0x18710e248",
        "literalLoadVa": "0x18710e766", "literalArgumentRegister": "rcx",
        "playbackCall": "Beyond.Gameplay.Actions.GameAction.PlayAudio",
        "playbackCallVa": "0x18710e773", "playbackParameter": "audioEventKey",
        "targetBinding": "scannedInteractiveModelGameObject", "triggerRole": "scanFeedbackLevel3",
    },
    "au_int_anchor_wave_brokensapling_active": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling", "consumerMethod": "_TickBroken",
        "methodIndex": 8790, "methodVa": "0x187146e90",
        "literalLoadVa": "0x187146edc", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling._PostAudioEvent",
        "playbackCallVa": "0x187146ee9", "playbackParameter": "audioEventName",
        "targetBinding": "anchorWaveSapling", "triggerRole": "brokenSaplingActiveTick",
    },
    "au_int_anchor_wave_brokensapling_idle_loop": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling", "consumerMethod": "Init",
        "methodIndex": 8780, "methodVa": "0x187145544",
        "literalLoadVa": "0x187145591", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling._PostAudioEvent",
        "playbackCallVa": "0x18714559e", "playbackParameter": "audioEventName",
        "targetBinding": "anchorWaveSapling", "triggerRole": "brokenSaplingInitialization",
    },
    "au_int_blightmiasma_screen_idle": {
        "consumerType": "Beyond.Gameplay.BlightMiasmaBrain", "consumerMethod": "_PlayMiasmaIdleAudio",
        "methodIndex": 11360, "methodVa": "0x18721cfa4",
        "literalLoadVa": "0x18721d025", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x18721d02f", "playbackParameter": "evt",
        "targetBinding": "blightMiasmaEntity", "triggerRole": "miasmaScreenIdle",
    },
    "au_int_blightmiasma_screen_enter": {
        "consumerType": "Beyond.Gameplay.BlightMiasmaBrain", "consumerMethod": "_EnableBlightMiasma",
        "methodIndex": 11367, "methodVa": "0x18721c958",
        "literalLoadVa": "0x18721cad6", "literalArgumentRegister": "rdx",
        "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.BlightMiasmaBrain._PlayMiasmaAudio",
        "playbackCallVa": "0x18721cae3", "playbackParameter": "eventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x18721cf6a",
        "targetBinding": "mainCharacterAudioObject", "triggerRole": "miasmaScreenEnter",
        "branchCondition": "_EnableBlightMiasma after enabling tolerance updates and screen effect",
    },
    "au_int_blightmiasma_screen_dying": {
        "consumerType": "Beyond.Gameplay.BlightMiasmaBrain", "consumerMethod": "_UpdateCurrentTolerance",
        "methodIndex": 11371, "methodVa": "0x18459c260",
        "literalLoadVa": "0x1852e1b5a", "literalArgumentRegister": "rdx",
        "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.BlightMiasmaBrain._PlayMiasmaAudio",
        "playbackCallVa": "0x1852e1b67", "playbackParameter": "eventName",
        "playbackSink": "Beyond.Gameplay.Audio.AudioManager.PostEvent", "playbackSinkVa": "0x183288a80",
        "playbackSinkInvocationVa": "0x18721cf6a",
        "targetBinding": "mainCharacterAudioObject", "triggerRole": "miasmaToleranceEnteredDanger",
        "branchCondition": "previous tolerance safe && updated tolerance enters danger threshold",
    },
    "au_int_erosion_sludge_under_scanner": {
        "consumerType": "Beyond.Gameplay.Core.ErosionSludgeCoreComponent", "consumerMethod": "OnBeginScanned",
        "methodIndex": 66946, "methodVa": "0x186eaa5b4",
        "literalLoadVa": "0x186eaa6cc", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186eaa6e8", "playbackParameter": "evt",
        "targetBinding": "erosionSludgeEntity", "triggerRole": "beginScanned",
    },
    "au_int_rune_column_disappear": {
        "consumerType": "Beyond.Gameplay.Core.InteractiveRuneAnchorPointComponent", "consumerMethod": "SetHideState",
        "methodIndex": 68437, "methodVa": "0x186ee4f7c",
        "literalLoadVa": "0x186ee5005", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186ee500c", "playbackParameter": "evt",
        "targetBinding": "runeAnchorEntity", "triggerRole": "hideStateDisappear",
    },
    "au_int_rune_column_reappear": {
        "consumerType": "Beyond.Gameplay.Core.InteractiveRuneAnchorPointComponent", "consumerMethod": "SetHideState",
        "methodIndex": 68437, "methodVa": "0x186ee4f7c",
        "literalLoadVa": "0x186ee4ff7", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186ee500c", "playbackParameter": "evt",
        "targetBinding": "runeAnchorEntity", "triggerRole": "hideStateReappear",
    },
    "au_int_seesaw_end": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicSeesaw", "consumerMethod": "_AudioEventEnd",
        "methodIndex": 10188, "methodVa": "0x187200c48",
        "literalLoadVa": "0x187200cb4", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x187200cbe", "playbackParameter": "evt",
        "targetBinding": "seesawEntity", "triggerRole": "seesawEnd",
    },
    "au_int_seesaw_shaking": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicSeesaw", "consumerMethod": "_AudioEventShaking",
        "methodIndex": 10189, "methodVa": "0x187200cf4",
        "literalLoadVa": "0x187200d60", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x187200d6a", "playbackParameter": "evt",
        "targetBinding": "seesawEntity", "triggerRole": "seesawShaking",
    },
    "au_int_seesaw_start": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicSeesaw", "consumerMethod": "_AudioEventStart",
        "methodIndex": 10187, "methodVa": "0x187200da0",
        "literalLoadVa": "0x187200e0c", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x187200e16", "playbackParameter": "evt",
        "targetBinding": "seesawEntity", "triggerRole": "seesawStart",
    },
    "au_int_telescopic_fold_end": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicTelescopic", "consumerMethod": "_AudioRetractPlateEnd",
        "methodIndex": 10322, "methodVa": "0x18720789c",
        "literalLoadVa": "0x187207908", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x187207912", "playbackParameter": "evt",
        "targetBinding": "telescopicEntity", "triggerRole": "retractPlateEnd",
    },
    "au_int_telescopic_fold_start": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicTelescopic", "consumerMethod": "_AudioRetractRailStart",
        "methodIndex": 10319, "methodVa": "0x187207aa0",
        "literalLoadVa": "0x187207b0c", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x187207b16", "playbackParameter": "evt",
        "targetBinding": "telescopicEntity", "triggerRole": "retractRailStart",
    },
    "au_int_telescopic_parapet_unfold_loop": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicTelescopic", "consumerMethod": "_AudioExtendRailStart",
        "methodIndex": 10316, "methodVa": "0x187207744",
        "literalLoadVa": "0x1872077b0", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1872077ba", "playbackParameter": "evt",
        "targetBinding": "telescopicEntity", "triggerRole": "extendRailStart",
    },
    "au_int_telescopic_plate_fold_loop": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicTelescopic", "consumerMethod": "_AudioRetractPlateStart",
        "methodIndex": 10320, "methodVa": "0x187207948",
        "literalLoadVa": "0x1872079b4", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1872079be", "playbackParameter": "evt",
        "targetBinding": "telescopicEntity", "triggerRole": "retractPlateStart",
    },
    "au_int_telescopic_unfold_end": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicTelescopic", "consumerMethod": "_AudioExtendRailEnd",
        "methodIndex": 10318, "methodVa": "0x187207698",
        "literalLoadVa": "0x187207704", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x18720770e", "playbackParameter": "evt",
        "targetBinding": "telescopicEntity", "triggerRole": "extendRailEnd",
    },
    "au_int_telescopic_unfold_start": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicTelescopic", "consumerMethod": "_AudioExtendPlateStart",
        "methodIndex": 10315, "methodVa": "0x1872075ec",
        "literalLoadVa": "0x187207658", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x187207662", "playbackParameter": "evt",
        "targetBinding": "telescopicEntity", "triggerRole": "extendPlateStart",
    },
    "au_int_wash_stain_tip": {
        "consumerType": "Beyond.Gameplay.InteractiveStainComponent", "consumerMethod": "OnCoreStateChanged",
        "methodIndex": 8608, "methodVa": "0x1870c3adc",
        "literalLoadVa": "0x1870c3bac", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1870c3bc8", "playbackParameter": "evt",
        "targetBinding": "stainEntity", "triggerRole": "coreStateChanged",
    },
    "au_int_water_start": {
        "consumerType": "Beyond.Gameplay.Core.WaterVolumeManager+WaterVolume", "consumerMethod": "_UpdateInfiniteWaterMeshPos",
        "methodIndex": 74956, "methodVa": "0x1870070f4",
        "literalLoadVa": "0x1870074b3", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1870074bd", "playbackParameter": "evt",
        "targetBinding": "infiniteWaterGameObject", "triggerRole": "infiniteWaterPositionUpdate",
    },
    "au_int_water_stop": {
        "consumerType": "Beyond.Gameplay.Core.WaterVolumeManager+WaterVolume", "consumerMethod": "_OnInfiniteWaterMeshPosUpdateFinished",
        "methodIndex": 74957, "methodVa": "0x187006e14",
        "literalLoadVa": "0x187006ebf", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x187006ec9", "playbackParameter": "evt",
        "targetBinding": "infiniteWaterGameObject", "triggerRole": "infiniteWaterPositionUpdateFinished",
    },
    "au_item_collect_common_3p": {
        "consumerType": "Beyond.Gameplay.Core.DropItemBehaviourComponent", "consumerMethod": "_PlayAudioDrop",
        "methodIndex": 66760, "methodVa": "0x183bee140",
        "literalLoadVa": "0x183bee20e", "literalArgumentRegister": "rcx",
        "playbackCall": "Beyond.Gameplay.Actions.GameAction.PlayAudioAtPosition",
        "playbackCallVa": "0x183bee227", "playbackParameter": "audioEventKey",
        "targetBinding": "dropItemPosition", "triggerRole": "itemDrop",
    },
    "au_ui_battle_enemy_imbalance": {
        "consumerType": "Beyond.Gameplay.Core.AbilitySystem+PoiseController", "consumerMethod": "ModifyPoise",
        "methodIndex": 54924, "methodVa": "0x1843c54e0",
        "literalLoadVa": "0x1843c5a77", "literalArgumentRegister": "rdx",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1843c5a81", "playbackParameter": "evt",
        "targetBinding": "abilityOwnerEntity", "triggerRole": "enemyPoiseImbalance",
    },
    "au_int_anchor_wave_idlesapling_hit": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling", "consumerMethod": "_ChangeState",
        "methodIndex": 8774, "methodVa": "0x187145bfc",
        "literalLoadVa": "0x187145cd4", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling._PostAudioEvent",
        "playbackCallVa": "0x187145ceb", "playbackParameter": "audioEventName",
        "targetBinding": "anchorWaveSapling", "triggerRole": "state4Hit",
        "branchCondition": "get_canBreak=false",
    },
    "au_int_anchor_wave_brokensapling_hit": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling", "consumerMethod": "_ChangeState",
        "methodIndex": 8774, "methodVa": "0x187145bfc",
        "literalLoadVa": "0x187145cdd", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "cmovne",
        "playbackCall": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling._PostAudioEvent",
        "playbackCallVa": "0x187145ceb", "playbackParameter": "audioEventName",
        "targetBinding": "anchorWaveSapling", "triggerRole": "state4Hit",
        "branchCondition": "get_canBreak=true",
    },
    "au_int_anchor_wave_idlesapling_destory": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling", "consumerMethod": "_ChangeState",
        "methodIndex": 8774, "methodVa": "0x187145bfc",
        "literalLoadVa": "0x187145cfa", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling._PostAudioEvent",
        "playbackCallVa": "0x187145d11", "playbackParameter": "audioEventName",
        "targetBinding": "anchorWaveSapling", "triggerRole": "state4Destroy",
        "branchCondition": "get_canBreak=false",
    },
    "au_int_anchor_wave_brokensapling_destory": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling", "consumerMethod": "_ChangeState",
        "methodIndex": 8774, "methodVa": "0x187145bfc",
        "literalLoadVa": "0x187145d03", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "cmovne",
        "playbackCall": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling._PostAudioEvent",
        "playbackCallVa": "0x187145d11", "playbackParameter": "audioEventName",
        "targetBinding": "anchorWaveSapling", "triggerRole": "state4Destroy",
        "branchCondition": "get_canBreak=true",
    },
    "au_int_anchor_wave_idlesapling_enterarea": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling", "consumerMethod": "_ChangeState",
        "methodIndex": 8774, "methodVa": "0x187145bfc",
        "literalLoadVa": "0x187145d6c", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling._PostAudioEvent",
        "playbackCallVa": "0x187145d83", "playbackParameter": "audioEventName",
        "targetBinding": "anchorWaveSapling", "triggerRole": "enterArea",
        "branchCondition": "get_canBreak=false",
    },
    "au_int_anchor_wave_brokensapling_enterarea": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling", "consumerMethod": "_ChangeState",
        "methodIndex": 8774, "methodVa": "0x187145bfc",
        "literalLoadVa": "0x187145d75", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "cmovne",
        "playbackCall": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Sapling._PostAudioEvent",
        "playbackCallVa": "0x187145d83", "playbackParameter": "audioEventName",
        "targetBinding": "anchorWaveSapling", "triggerRole": "enterArea",
        "branchCondition": "get_canBreak=true",
    },
    "au_int_anchor_wave_movingsapling_hit": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Slug", "consumerMethod": "_PostOnHitAudioEvent",
        "methodIndex": 8807, "methodVa": "0x187147940",
        "literalLoadVa": "0x1871479a3", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1871479bf", "playbackParameter": "evt",
        "targetBinding": "movingSaplingEntity", "triggerRole": "onHitFirstEvent",
        "branchCondition": "unpatchedMethodPath",
    },
    "au_int_anchor_wave_movingsapling_destory": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicAnchorWaveCore+Slug", "consumerMethod": "_PostOnHitAudioEvent",
        "methodIndex": 8807, "methodVa": "0x187147940",
        "literalLoadVa": "0x1871479d6", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x1871479e1", "playbackParameter": "evt",
        "targetBinding": "movingSaplingEntity", "triggerRole": "onHitSecondEvent",
        "branchCondition": "unpatchedMethodPath",
    },
    "au_int_box_touch": {
        "consumerType": "Beyond.Gameplay.Core.PushableComponent", "consumerMethod": "_SetState",
        "methodIndex": 69381, "methodVa": "0x186f117d4",
        "literalLoadVa": "0x186f11886", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186f11890", "playbackParameter": "evt",
        "targetBinding": "pushableAudioObject", "triggerRole": "enterState2",
        "branchCondition": "previousState!=2 && newState==2",
    },
    "au_int_box_move_stop": {
        "consumerType": "Beyond.Gameplay.Core.PushableComponent", "consumerMethod": "_SetState",
        "methodIndex": 69381, "methodVa": "0x186f117d4",
        "literalLoadVa": "0x186f118c5", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186f118cf", "playbackParameter": "evt",
        "targetBinding": "pushableAudioObject", "triggerRole": "leaveState2",
        "branchCondition": "previousState==2 && newState!=2",
    },
    "au_int_box_fall_high": {
        "consumerType": "Beyond.Gameplay.Core.PushableComponent", "consumerMethod": "_SetState",
        "methodIndex": 69381, "methodVa": "0x186f117d4",
        "literalLoadVa": "0x186f11903", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186f1192d", "playbackParameter": "evt",
        "targetBinding": "pushableAudioObject", "triggerRole": "leaveState4FallBranch",
        "branchCondition": "previousState==4 && newState!=4 && m_fallSpeed<=10.0",
    },
    "au_int_box_fall_low": {
        "consumerType": "Beyond.Gameplay.Core.PushableComponent", "consumerMethod": "_SetState",
        "methodIndex": 69381, "methodVa": "0x186f117d4",
        "literalLoadVa": "0x186f11911", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        "playbackCall": "Beyond.Gameplay.Audio.AudioManager.PostEvent",
        "playbackCallVa": "0x186f1192d", "playbackParameter": "evt",
        "targetBinding": "pushableAudioObject", "triggerRole": "leaveState4FallBranch",
        "branchCondition": "previousState==4 && newState!=4 && m_fallSpeed>10.0",
    },
    "au_fac_amb_opening": {
        "consumerType": "Beyond.Gameplay.Audio.AudioRemoteFactoryBridge", "consumerMethod": "TriggerFactoryMainRegionAudio",
        "methodIndex": 39720, "methodVa": "0x1846bcc00",
        "literalLoadVa": "0x1846bccce", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        "playbackCall": "nativeStringEventWrapper",
        "playbackCallVa": "0x183287c90", "playbackParameter": "eventName",
        "playbackHashCall": "Beyond.Audio.AudioHashGenerator.Compute", "playbackHashCallVa": "0x18328dcd0",
        "playbackSink": "Beyond.Audio.AudioAdapter._PostEvent", "playbackSinkVa": "0x18328a690",
        "targetBinding": "globalAudioObject", "triggerRole": "factoryMainRegionOpening",
        "branchCondition": "directTailCallAfterFactoryAnnouncement",
    },
    "au_ui_battle_combo_skill": {
        "consumerType": "Beyond.Gameplay.Core.BattleManager", "consumerMethod": "PendingComboSkill",
        "methodIndex": 59554, "methodVa": "0x186d7411c",
        "literalLoadVa": "0x186d745d9", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        "playbackCall": "nativeStringEventWrapper",
        "playbackCallVa": "0x183287c90", "playbackParameter": "eventName",
        "playbackHashCall": "Beyond.Audio.AudioHashGenerator.Compute", "playbackHashCallVa": "0x18328dcd0",
        "playbackSink": "Beyond.Audio.AudioAdapter._PostEvent", "playbackSinkVa": "0x18328a690",
        "targetBinding": "globalAudioObject", "triggerRole": "pendingComboSkillUiCue",
        "branchCondition": "r14d!=0 timing branch before PlayComboSkillVoice",
    },
    "au_ui_event_inventory_destory_animation": {
        "consumerType": "Beyond.Gameplay.AbandonPackSystem", "consumerMethod": "_HandlePackCreateMessage",
        "methodIndex": 15569, "methodVa": "0x1872b1fd8",
        "literalLoadVa": "0x1872b2086", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "abandonPackCreateAnimation",
    },
    "au_ui_event_remote_start": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.MainCharRemoteCommBrain", "consumerMethod": "_PostAudioEvent",
        "methodIndex": 83168, "methodVa": "0x1870f4810",
        "literalLoadVa": "0x1870f485d", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "remoteCommunicationStart",
        "branchCondition": "unpatchedMethodPath",
    },
    "au_ui_event_spaceshipscreen_pageflip": {
        "consumerType": "SpaceShipReceptionRoomImagePoster", "consumerMethod": "_EnqueueImagePoster",
        "methodIndex": 163, "methodVa": "0x186a8db0c",
        "literalLoadVa": "0x186a8dbfb", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_POSITION_EVENT_PLAYBACK,
        "targetBinding": "imagePosterWorldPosition", "triggerRole": "spaceshipImagePosterPageFlip",
    },
    "au_ui_hud_hiddentube_outofrange": {
        "consumerType": "Beyond.Gameplay.RemoteFactory.RemoteFactoryEventHandler", "consumerMethod": "OnUdpipeConnectPreviewOutOfRange",
        "methodIndex": 29012, "methodVa": "0x182abf3a0",
        "literalLoadVa": "0x182abf8f6", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "udpipeConnectPreviewOutOfRange",
    },
    "au_ui_mission_step_target": {
        "consumerType": "Beyond.Gameplay.MissionTrackerUpdate", "consumerMethod": "UpdateMissionTrackers",
        "methodIndex": 21308, "methodVa": "0x1830a4ec0",
        "literalLoadVa": "0x1830a51fa", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "missionTrackerStepTargetUpdate",
    },
    "au_ui_plant_cultivation": {
        "consumerType": "Beyond.Gameplay.Core.IntFacSoilComponent", "consumerMethod": "_DoReclaim",
        "methodIndex": 69046, "methodVa": "0x186ef1240",
        "literalLoadVa": "0x186ef129b", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "soilReclaimOperation",
        "branchCondition": "isDisableInteract=false",
    },
    "au_ui_plant_gather": {
        "consumerType": "Beyond.Gameplay.Core.IntFacSoilComponent", "consumerMethod": "_DoHarvest",
        "methodIndex": 69047, "methodVa": "0x186ef0f14",
        "literalLoadVa": "0x186ef0f6f", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "soilHarvestOperation",
        "branchCondition": "isDisableInteract=false",
    },
    "au_ui_plant_water": {
        "consumerType": "Beyond.Gameplay.Core.IntFacSoilComponent", "consumerMethod": "_DoWatering",
        "methodIndex": 69045, "methodVa": "0x186ef12e4",
        "literalLoadVa": "0x186ef133f", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "soilWateringOperation",
        "branchCondition": "isDisableInteract=false",
    },
    "au_ui_toast_snsnewdialogtoast_open": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.MainCharForceSNSBrain+<_ShowStartCoroutine>d__106", "consumerMethod": "MoveNext",
        "methodIndex": 83119, "methodVa": "0x1871026d8",
        "literalLoadVa": "0x187102bc0", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "snsNewDialogToastOpen",
    },
    "au_ui_toast_tasktrack_countdowntoast_rank": {
        "consumerType": "Beyond.UI.UIRaceModuleRankController", "consumerMethod": "_UpdateRaceModuleRank",
        "methodIndex": 426688, "methodVa": "0x18b144c24",
        "literalLoadVa": "0x18b144d73", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "raceModuleRankUpdate",
    },
    "au_eny_general_death_dissolve": {
        "consumerType": "Beyond.Gameplay.Core.EnemyController", "consumerMethod": "OnDie",
        "methodIndex": 64304, "methodVa": "0x18420f8a0",
        "literalLoadVa": "0x184211c00", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_POSITION_EVENT_PLAYBACK,
        "targetBinding": "enemyDeathWorldPosition", "triggerRole": "enemyDeathDissolve",
    },
    "au_global_dungeon_reset": {
        "consumerType": "Beyond.Gameplay.Audio.AudioManager", "consumerMethod": "OnMapReset",
        "methodIndex": 38912, "methodVa": "0x186ac3470",
        "literalLoadVa": "0x186ac34c4", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "mapReset",
    },
    "au_int_erosion_disappear": {
        "consumerType": "Beyond.Gameplay.Core.DynamicScene.DynamicSceneErosionSystem", "consumerMethod": "_StartErosionPerformance",
        "methodIndex": 84027, "methodVa": "0x1871175ec",
        "literalLoadVa": "0x1871177e9", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_POSITION_EVENT_PLAYBACK,
        "targetBinding": "erosionWorldPosition", "triggerRole": "erosionPerformanceStart",
    },
    "au_int_factory_upgrade_bot_interact": {
        "consumerType": "Beyond.Gameplay.Core.FacRegionUpgradeSystemComponent", "consumerMethod": "_OpenFacRegionUpgradePanel",
        "methodIndex": 67043, "methodVa": "0x186ec4558",
        "literalLoadVa": "0x186ec45d4", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "openFactoryRegionUpgradePanel",
    },
    "au_int_forge_iron_success": {
        "consumerType": "Beyond.UI.ForgeIronTemperatureCircleUI", "consumerMethod": "_SetState",
        "methodIndex": 426287, "methodVa": "0x18b12b90c",
        "literalLoadVa": "0x18b12bb49", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "forgeIronSuccessState",
    },
    "au_int_mining_machine_eject": {
        "consumerType": "Beyond.Gameplay.InteractiveLogicRotatePlatform", "consumerMethod": "_EnterIdleRunningState",
        "methodIndex": 10129, "methodVa": "0x1871fdf08",
        "literalLoadVa": "0x1871fdf55", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "rotatePlatformEnterIdleRunning",
    },
    "au_int_socialcircle_active": {
        "consumerType": "Beyond.Gameplay.Factory.FactorySocialBuildingCircleEffectCtrl", "consumerMethod": "_PlaySoundEffect",
        "methodIndex": 26306, "methodVa": "0x1874d2030",
        "literalLoadVa": "0x1874d20dc", "literalArgumentRegister": "rdi", "literalArgumentInstruction": "mov",
        **NATIVE_POSITION_EVENT_PLAYBACK,
        "targetBinding": "socialBuildingWorldPosition", "triggerRole": "socialCircleActivate",
        "branchCondition": "requestedState==2 && currentState==3",
    },
    "au_int_socialcircle_inactive": {
        "consumerType": "Beyond.Gameplay.Factory.FactorySocialBuildingCircleEffectCtrl", "consumerMethod": "_PlaySoundEffect",
        "methodIndex": 26306, "methodVa": "0x1874d2030",
        "literalLoadVa": "0x1874d20f3", "literalArgumentRegister": "rdi", "literalArgumentInstruction": "mov",
        **NATIVE_POSITION_EVENT_PLAYBACK,
        "targetBinding": "socialBuildingWorldPosition", "triggerRole": "socialCircleDeactivate",
        "branchCondition": "requestedState==3 && currentState==2",
    },
    "au_int_systempoi_building_dissolve": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.InteractiveUpgradePerformBrain", "consumerMethod": "_SetupModelChangeTimer",
        "methodIndex": 82885, "methodVa": "0x1870e8d0c",
        "literalLoadVa": "0x1870e8e95", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_POSITION_EVENT_PLAYBACK,
        "targetBinding": "upgradeBuildingWorldPosition", "triggerRole": "buildingModelDissolve",
    },
    "au_int_systempoi_building_generated": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.InteractiveUpgradePerformBrain", "consumerMethod": "_AfterModelChange",
        "methodIndex": 82892, "methodVa": "0x1870e80ac",
        "literalLoadVa": "0x1870e81de", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_POSITION_EVENT_PLAYBACK,
        "targetBinding": "upgradeBuildingWorldPosition", "triggerRole": "buildingModelGenerated",
    },
    "au_int_water_outlet_cdg004_working": {
        "consumerType": "Beyond.Gameplay.Core.InteractiveOutFallComponent", "consumerMethod": "OnCoreStateChanged",
        "methodIndex": 68324, "methodVa": "0x186edfde4",
        "literalLoadVa": "0x186edfedf", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "waterOutfallWorkingState",
        "branchCondition": "newCoreState!=0",
    },
    "au_ui_belt_confirm": {
        "consumerType": "Beyond.Gameplay.RemoteFactory.RemoteFactoryEventHandler", "consumerMethod": "OnConveyorWholeConfirmed",
        "methodIndex": 28989, "methodVa": "0x18752bcfc",
        "literalLoadVa": "0x18752bd49", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "conveyorWholeConfirmed",
    },
    "au_ui_btn_info_map": {
        "consumerType": "Beyond.Gameplay.Actions.ShowEnterDungeonUI", "consumerMethod": "Execute",
        "methodIndex": 36132, "methodVa": "0x18766ceb8",
        "literalLoadVa": "0x18766cf92", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "showEnterDungeonUi",
    },
    "au_ui_char_campfire_revive": {
        "consumerType": "Beyond.Gameplay.Core.SquadManager", "consumerMethod": "_OnRest",
        "methodIndex": 60487, "methodVa": "0x183a99a30",
        "literalLoadVa": "0x183a99ba9", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "squadRestCampfireRevive",
    },
    "au_ui_char_revive": {
        "consumerType": "Beyond.Gameplay.Core.SquadManager", "consumerMethod": "_OnReviveByItem",
        "methodIndex": 60491, "methodVa": "0x186db37e0",
        "literalLoadVa": "0x186db3a77", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_POSITION_EVENT_PLAYBACK,
        "targetBinding": "revivedCharacterWorldPosition", "triggerRole": "reviveCharacterByItem",
    },
    "au_ui_exceed_cast_distance": {
        "consumerType": "Beyond.Gameplay.Core.Skill", "consumerMethod": "_StartShowOutOfRangeHint",
        "methodIndex": 53890, "methodVa": "0x186ca7c18",
        "literalLoadVa": "0x186ca8063", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "skillCastOutOfRangeHint",
    },
    "au_ui_fac_checkerboard_fail": {
        "consumerType": "Beyond.Gameplay.RemoteFactory.RemoteFactoryEventHandler", "consumerMethod": "OnBuildingPreviewPositionRotationChanged",
        "methodIndex": 29002, "methodVa": "0x18752ba14",
        "literalLoadVa": "0x18752ba60", "literalArgumentRegister": "rbx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "factoryCheckerboardPlacementFail",
        "branchCondition": "positionRotationValid=false",
    },
    "au_ui_fac_no_power": {
        "consumerType": "Beyond.Gameplay.RemoteFactory.RemoteFactoryEventHandler", "consumerMethod": "OnChapterPowerOutage",
        "methodIndex": 28984, "methodVa": "0x18752babc",
        "literalLoadVa": "0x18752bb23", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "factoryChapterPowerOutage",
    },
    "au_ui_medicine_read": {
        "consumerType": "Beyond.Gameplay.Core.AbilitySystem+TacticalItem", "consumerMethod": "_Cast",
        "methodIndex": 55016, "methodVa": "0x186cc6338",
        "literalLoadVa": "0x186cc6843", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "tacticalMedicineCast",
    },
    "au_ui_power_pole_connect": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.PowerPoleBrain", "consumerMethod": "DoLinkFacPowerPole",
        "methodIndex": 83212, "methodVa": "0x1870f6778",
        "literalLoadVa": "0x1870f695d", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "factoryPowerPoleLinked",
    },
    "au_ui_recover_skill": {
        "consumerType": "Beyond.Gameplay.Core.ObtainCostAction", "consumerMethod": "ExecuteInternal",
        "methodIndex": 56881, "methodVa": "0x184246060",
        "literalLoadVa": "0x184246fa6", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "recoverSkillCostAction",
    },
    "au_ui_scan": {
        "consumerType": "Beyond.Gameplay.ScanInteractive", "consumerMethod": "Scan",
        "methodIndex": 15540, "methodVa": "0x1872b80c8",
        "literalLoadVa": "0x1872b836b", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "interactiveScan",
    },
    "au_ui_sprint_errors": {
        "consumerType": "Beyond.UI.UIMainCharFootBarArc", "consumerMethod": "_OnDashFailed",
        "methodIndex": 426053, "methodVa": "0x18b12f770",
        "literalLoadVa": "0x18b12f7c9", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "dashFailed",
    },
    "au_ui_ultskill_cd_complete": {
        "consumerType": "Beyond.UI.SkillButton", "consumerMethod": "OnUspChange",
        "methodIndex": 425705, "methodVa": "0x183d40940",
        "literalLoadVa": "0x183d41298", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_FORWARDER_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "ultimateSkillCooldownComplete",
    },
    "au_vibration_common_action_fail": {
        "consumerType": "Beyond.UI.MobileMotionManager", "consumerMethod": "PostEventCommonOperateFailure",
        "methodIndex": 400620, "methodVa": "0x18b0f7e48",
        "literalLoadVa": "0x18b0f7e7d", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        **NATIVE_MOBILE_MOTION_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "commonOperationFailureMotion",
        "branchCondition": "controllerCachedMotion && motionManagerEnabled",
    },
    "au_vibration_common_action_success": {
        "consumerType": "Beyond.UI.MobileMotionManager", "consumerMethod": "PostEventCommonOperateSuccess",
        "methodIndex": 400619, "methodVa": "0x18b0f7ebc",
        "literalLoadVa": "0x18b0f7ef1", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        **NATIVE_MOBILE_MOTION_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "commonOperationSuccessMotion",
        "branchCondition": "controllerCachedMotion && motionManagerEnabled",
    },
    "au_vibration_common_short": {
        "consumerType": "Beyond.UI.MobileMotionManager", "consumerMethod": "PostEventCommonShort",
        "methodIndex": 400618, "methodVa": "0x18b0f7f30",
        "literalLoadVa": "0x18b0f7f65", "literalArgumentRegister": "rdx", "literalArgumentInstruction": "mov",
        **NATIVE_MOBILE_MOTION_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "commonShortMotion",
        "branchCondition": "controllerCachedMotion && motionManagerEnabled",
    },
    "au_ui_hud_powertower_count_units": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.LinkWireBrain", "consumerMethod": "_UpdateLine",
        "methodIndex": 83029, "methodVa": "0x1870ec404",
        "literalLoadVa": "0x1870ec76c", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "powerTowerCountUnitsUpdate",
        "branchCondition": "quantizedCount comparison at 0x1870ec75a takes not-above path",
    },
    "au_ui_hud_powertower_count_tens": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.LinkWireBrain", "consumerMethod": "_UpdateLine",
        "methodIndex": 83029, "methodVa": "0x1870ec404",
        "literalLoadVa": "0x1870ec90a", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "powerTowerCountTensUpdate",
        "branchCondition": "quantizedCount comparison at 0x1870ec75a takes above path",
    },
    "au_ui_power_pole_stayguy": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.LinkWireBrain", "consumerMethod": "BeginLink",
        "methodIndex": 83018, "methodVa": "0x1870e9f54",
        "literalLoadVa": "0x1870ea2f7", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "beginPowerPoleLink",
        "branchCondition": "linkType==1",
    },
    "au_ui_udpipe_stayguy": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.LinkWireBrain", "consumerMethod": "BeginLink",
        "methodIndex": 83018, "methodVa": "0x1870e9f54",
        "literalLoadVa": "0x1870ea2e2", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "beginUdpipeLink",
        "branchCondition": "linkType==2",
    },
    "au_ui_udpipe_connect": {
        "consumerType": "Beyond.Gameplay.Core.GameMech.LinkWireBrain", "consumerMethod": "DoLinkUdpipe",
        "methodIndex": 83023, "methodVa": "0x1870ea644",
        "literalLoadVa": "0x1870ea866", "literalArgumentRegister": "rcx", "literalArgumentInstruction": "mov",
        **NATIVE_STRING_EVENT_PLAYBACK,
        "targetBinding": "globalAudioObject", "triggerRole": "udpipeConnectionAccepted",
        "branchCondition": "linkCommitGuard [this+0x22]==false",
    },
}
def collect_contexts(
    metadata_path: Path | None,
    *,
    native_context: native_evidence.NativeAudioEvidence,
    current_wwise_event_hashes: set[int] | None = None,
) -> tuple[dict[str, list[dict[str, Any]]], list[str]]:
    names = [
        name for name in identifiers.collect_metadata_audio_literals(metadata_path)
        if not identifiers.is_rtpc_parameter_name(name)
    ]
    contexts: dict[str, list[dict[str, Any]]] = defaultdict(list)
    seen: dict[str, set[str]] = defaultdict(set)
    callsite_contexts: dict[str, dict[str, Any]] = {}
    metadata_fingerprint = native_context.metadata_sha256
    gameassembly_fingerprint = native_context.gameassembly_sha256
    if native_context.validated:
        callsite_contexts = MANAGED_AUDIO_CALLSITE_CONTEXTS
    for name in names:
        event_hash = identifiers.audio_hash_generator_compute(name)
        if (
            current_wwise_event_hashes is not None
            and event_hash not in current_wwise_event_hashes
        ):
            continue
        callsite = callsite_contexts.get(name.lower())
        context = {
            "kind": "binaryManagedLiteralCallsite" if callsite else "binaryManagedLiteral",
            "literal": name,
            "eventHash": event_hash,
            "eventHashHex": f"0x{event_hash:08x}",
            "source": "Endfield_Data/il2cpp_data/Metadata/global-metadata.dat:stringLiteral",
            "evidence": (
                "exactManagedStringLiteralCurrentWwiseEventHashAndNativePlaybackCallsite"
                if callsite else "exactManagedStringLiteralAndCurrentWwiseEventHash"
            ),
            "playbackPlacementStatus": (
                "exactManagedNativePlaybackCallsite"
                if callsite else "identityOnlyManagedStringLiteral"
            ),
            "runtimeConsumerStatus": (
                "exactCurrentBuildNativeConsumer"
                if callsite else "consumerCallsiteUnresolved"
            ),
        }
        if callsite:
            context.update(callsite)
            context.update({
                "metadataSha256": metadata_fingerprint,
                "gameAssemblySha256": gameassembly_fingerprint,
                "runtimeExecutionStatus": "runtimeBranchExecutionUnobserved",
            })
        context_utils.append_context(contexts, seen, name, context)
    return dict(contexts), names
