// Generated by tools/build_endminf_m31_peak_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM31PeakCaptureData
    {
        internal const string SourceSession = "20260827T183054Z";
        internal const int SourceFrame = 1818;
        internal const float PhaseSeconds = 4.350000f;
        internal const int DrawCount = 2;
        internal const bool PayloadPrepared = true;
        internal const bool DepthContractReady = true;
        internal const string MetadataSha256 = "e1e5402c043c51bc5e32e7619357884fc505b2aca29425a2577dfeaa571ca04b";
        internal const string TextureT1Sha256 = "faa8e27acd0e887456212f4f281b5cc897442ad7ebf8415db2fe3f164d381bc0";
    }
}
