// Generated by tools/build_endminf_m30_exact_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM30ExactCaptureData
    {
        internal const string TemporalSourceSession = "20260827T183054Z";
        internal const string ResourceSourceSession = "20260827T183054Z";
        internal const string TemporalReportSha256 = "25f3cadc7ca27f18e4c420925cbf70a7566fb546966cbd8d5a541310ec5ccf20";
        internal const string TextureT1Sha256 = "faa8e27acd0e887456212f4f281b5cc897442ad7ebf8415db2fe3f164d381bc0";
        internal const bool PayloadPrepared = true;
        internal const bool DepthContractReady = true;
        internal const int PacketCount = 6;
        internal static readonly int[] SourceFrames = { 1753, 1764, 1775, 1785, 1796, 1807 };
        internal static readonly float[] PhaseSeconds = { 2.983333f, 3.200000f, 3.450000f, 3.683333f, 3.916667f, 4.133333f };
        internal static readonly int[] IndexCounts = { 12, 6, 6, 6, 6, 12 };
    }
}
