// Generated by tools/build_endminf_m31_peak_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM31PeakCaptureData
    {
        internal const string TemporalSourceSession = "20260828T121603Z";
        internal const string PayloadSourceSession = "20260827T183054Z";
        internal const int PayloadSourceFrame = 1818;
        internal const int AnchorFrame = 1977;
        internal const float AnchorPhaseSeconds = 4.350000f;
        internal const int QpcFrequency = 10000000;
        internal const int PacketCount = 9;
        internal const int NativePayloadDrawCount = 2;
        internal const bool PayloadPrepared = true;
        internal const bool DepthContractReady = true;
        internal const string PayloadMetadataSha256 = "e1e5402c043c51bc5e32e7619357884fc505b2aca29425a2577dfeaa571ca04b";
        internal const string TextureT1Sha256 = "faa8e27acd0e887456212f4f281b5cc897442ad7ebf8415db2fe3f164d381bc0";
        internal static readonly int[] SourceFrames = { 1896, 1907, 1918, 1929, 1941, 1954, 1965, 1977, 1989 };
        internal static readonly float[] PhaseSeconds = { 2.863329f, 3.063143f, 3.263229f, 3.462984f, 3.679626f, 3.929817f, 4.129770f, 4.350000f, 4.564017f };
        internal static readonly int[] DrawCounts = { 2, 2, 2, 2, 2, 2, 2, 3, 1 };
        internal static readonly int[] FirstDrawOrdinals = { 68, 68, 68, 77, 77, 68, 77, 66, 67 };
        internal static readonly int[] LastDrawOrdinals = { 77, 79, 79, 89, 89, 80, 89, 89, 67 };
        internal static readonly bool[] NativeOrderCompatible = { false, false, false, false, false, false, false, false, true };
        internal static readonly bool[] SplitOrderCompatible = { true, true, true, true, true, true, true, false, false };
        internal static readonly int[] InterleavedM29M30Counts = { 2, 2, 2, 2, 2, 2, 2, 0, 0 };
        internal static readonly string[] TemporalMetadataSha256 = { "0b3e01b79571ffefea96f8e85003175c5d84e19b13e6f36ada8ae732f63a0a3d", "670e3bb377b0543bd41ada162658b271de65126e9eeb3fc61353f87c5a99056f", "a11b69b7c272962d9fd520e669067ed85aa3a487d90681dca0bbd61e9d71b1f9", "2febf2b8d695a875e47a703bf257b41e40c839c01014353fdd85e7bd33a1359a", "80a27368912493b3174d16da456b886d21d40a26cc411a2961f24ca61fe15feb", "1b679b6812dd900601658215ded73a93b508e92fe59ee73874ef61fbf82745e9", "d5e2befceb977423b0f70cf54e1e8164f91a178f71dc928dd8c5b576026dd21e", "b5029723d017bb9a558eff0df96c58fedae7ffeeac6a92c03ffaae4ee32604e2", "65989294287f6c09b7f81257a55bda950c55acee089151cb294fd10b03412665" };
    }
}
