// Generated by tools/build_endminf_m14_exact_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM14ExactCaptureData
    {
        internal const string SourceSession = "20260826T091023Z";
        internal const string SourceReportSha256 = "3affeb8dfde441641cc3dab0263cff2fbe0c6ff688f362e004ac10d8b294d16f";
        internal const int PacketCount = 7;
        internal static readonly int[] SourceFrames = { 1405, 1413, 1421, 1429, 1437, 1445, 1453 };
        internal static readonly float[] PhaseSeconds = { 4.50f, 4.75f, 5.00f, 5.25f, 5.50f, 5.75f, 6.00f };
        internal static readonly int[] IndexCounts = { 1968, 2880, 2862, 2490, 2076, 1662, 1296 };
    }
}
