// Generated by tools/build_endminf_m18_peak_exact_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM18PeakCaptureData
    {
        internal const string SourceSession = "20260828T004942Z";
        internal const int SourceFrame = 2775;
        internal const int DrawOrdinal = 82;
        internal const float PhaseSeconds = 4.500000f;
        internal const int DrawCount = 1;
        internal const bool PayloadPrepared = true;
        internal const string MetadataSha256 = "6038aec199ba5493cbadbed94594fad39c943e9215bc653b756facf0d2f3982e";
        internal const string ResourcesSha256 = "0d6127cd7a89935d352000326b6253445bd9fcee504462ec2679e859e26413e9";
        internal const string VertexSha256 = "c798b3374ff03684ec536db43d6261377de03b40eddeb0c00e36a8b8ddde8c2c";
        internal const string IndexSha256 = "df1ffa56baa56e8ed36e6fa78b12ff76bdbf801dc8ce3c4496633b81138eb57c";
    }
}
