// Generated by tools/build_endminf_m27_temporal_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM27TemporalCaptureData
    {
        internal const string SourceSession = "20260826T162514Z";
        internal const string SourceReportSha256 = "7e27593ced728931dad6737ab5f2cd2204959f4a47363ff000eca59aff66069a";
        internal const int PacketCount = 16;
        internal const int TotalDrawCount = 39;
        internal static readonly int[] SourceFrames = { 2905, 2913, 2921, 2929, 2937, 2945, 2953, 2962, 2970, 2978, 2987, 2995, 3003, 3011, 3019, 3027 };
        internal static readonly float[] PhaseSeconds = { 4.500000f, 4.633333f, 4.766667f, 4.900000f, 5.033333f, 5.166667f, 5.300000f, 5.450000f, 5.583333f, 5.716667f, 5.866667f, 6.000000f, 6.133333f, 6.266667f, 6.400000f, 6.533333f };
        internal static readonly int[] DrawCounts = { 4, 4, 4, 4, 4, 4, 4, 4, 0, 1, 1, 1, 1, 1, 1, 1 };
    }
}
