// Generated by tools/build_endminf_m29_exact_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM29ExactCaptureData
    {
        internal const string SourceSession = "20260827T183054Z";
        internal const string DrawContractSession = "20260827T225644Z";
        internal const string ReportSha256 = "25f3cadc7ca27f18e4c420925cbf70a7566fb546966cbd8d5a541310ec5ccf20";
        internal const string DrawContractReportSha256 = "c13a5d79cacadae35c151b76da8aa74f1191c2ebb155a616a17d723ba49b81e0";
        internal const string TextureT0Sha256 = "9447292a55b8eabe5c3254ab91fcd97b28d911062ae742f23dea49d978113c41";
        internal const string TextureT1Sha256 = "c8dfd6f4954922e72bc669845cd548c17ec1a40957b738c410c06604bdde86cb";
        internal const bool PayloadPrepared = true;
        internal const bool GeometryContractReady = true;
        internal const int PacketCount = 9;
        internal static readonly int[] SourceFrames = { 1732, 1743, 1753, 1764, 1775, 2723, 1785, 1796, 1807 };
        internal static readonly int[] GeometrySourceFrames = { 1732, 1743, 1753, 1764, 2723, 2723, 2723, 2723, 2723 };
        internal static readonly float[] PacketPhases = { 2.550000f, 2.733333f, 2.983333f, 3.200000f, 3.450000f, 3.600000f, 3.683333f, 3.916667f, 4.133333f };
        internal static readonly int[] VertexStrides = { 60, 60, 60, 60, 60, 60, 60, 60, 60 };
    }
}
