// Generated by tools/build_endminf_m20_peak_exact_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM20PeakCaptureData
    {
        internal const string SourceSession = "20260828T224210Z";
        internal const int SourceFrame = 1748;
        internal const int DrawOrdinal = 77;
        internal const float PhaseSeconds = 4.433333f;
        internal const bool PayloadPrepared = true;
        internal const string AtlasSha256 = "c7d830bcee33bbd31367d2c7d40eeb9f0d5d808f94d66925fb4fda619fcc8bdd";
    }
}
