// Generated by tools/build_endminf_m28_peak_exact_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM28PeakCaptureData
    {
        internal const string SourceSession = "20260828T004942Z";
        internal const int SourceFrame = 2775;
        internal const int DrawOrdinal = 87;
        internal const float PhaseSeconds = 4.500000f;
        internal const int DrawCount = 1;
        internal const bool PayloadPrepared = true;
        internal const string MetadataSha256 = "6038aec199ba5493cbadbed94594fad39c943e9215bc653b756facf0d2f3982e";
        internal const string ResourcesSha256 = "0d6127cd7a89935d352000326b6253445bd9fcee504462ec2679e859e26413e9";
        internal const string VertexSha256 = "d0330e2efed3c8916d85f3ed6c4cce71720c63980fcb4e09c1607e9a0954a8c3";
        internal const string IndexSha256 = "321f2046a4b0fda3555920d5bf8e92fd530d9a28fd1819959516b9f726194583";
    }
}
