// Generated by tools/build_endminf_vfxbasev2_peak_cohort.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredVFXBaseV2PeakCohortData
    {
        internal const string SourceSession = "20260827T225644Z";
        internal const string ReportSha256 = "c13a5d79cacadae35c151b76da8aa74f1191c2ebb155a616a17d723ba49b81e0";
        internal const int SourceFrame = 2723;
        internal const bool PayloadPrepared = true;
        internal const int DrawCount = 15;
        internal const int TextureCount = 5;
        internal static readonly int[] DrawOrdinals = { 68, 74, 75, 76, 77, 78, 79, 80, 81, 83, 84, 85, 86, 87, 88 };
        internal static readonly int[] DrawIndices = { 3, 12, 19, 20, 28, 29, 8, 9, 11, 15, 16, 17, 24, 25, 31 };
        internal static readonly int[] IndexCounts = { 6, 6, 6, 6, 12, 240, 144, 12, 6, 6, 6, 6, 6, 12, 18 };
        internal static readonly string[] TextureSha256 = { "faa8e27acd0e887456212f4f281b5cc897442ad7ebf8415db2fe3f164d381bc0", "c7d830bcee33bbd31367d2c7d40eeb9f0d5d808f94d66925fb4fda619fcc8bdd", "9bd3287e6aca8e3bfe32d1ec53d95804ed7f6afa23cdd4a8d5ce736891e0f98f", "60bfe7ce2b87d0360adcbe9e06298b14a754ba16e8902f792c2e13f15cb933c6", "4c4a9104e58332414e1772c07e6d5dc6adaaa6b331c4fe68725387378492d0ec" };
    }
}
