// Generated by tools/build_endminf_m21_peak_exact_capture_data.py. Do not edit.
namespace EndfieldGraphShaderLab
{
    internal static class EndfieldRecoveredM21PeakCaptureData
    {
        internal const string SourceSession = "20260828T004942Z";
        internal const int SourceFrame = 2775;
        internal const int DrawOrdinal = 74;
        internal const float PhaseSeconds = 4.500000f;
        internal const int DrawCount = 1;
        internal const bool PayloadPrepared = true;
        internal const string MetadataSha256 = "6038aec199ba5493cbadbed94594fad39c943e9215bc653b756facf0d2f3982e";
        internal const string ResourcesSha256 = "0d6127cd7a89935d352000326b6253445bd9fcee504462ec2679e859e26413e9";
        internal const string VertexSha256 = "463aa8a3d7956663a3384848b76ee4239ad1bb21a9126010d4c166cbbb2bca92";
        internal const string IndexSha256 = "b68918aa41db6e3cea9b23bd95a5053525e56089931dab3a5d6c711bbefcb61c";
    }
}
